import os
import tempfile
import zipfile
from pathlib import Path
from typing import Dict, Optional


SH_GENERATE_DOT = "script/sh/generateDot.sh"
SOOT_JAR_PATH = "soot-4.4.1-jar-with-dependencies.jar"
CATEGORY_LIBRARY = "library_like"
CATEGORY_AUTOGENERATED = "autogenerated_like"
CATEGORY_PACKAGING = "packaging_noise"
CATEGORY_UNSTABLE = "unstable_extraction_risk"
EXCLUDED_NOISE_CATEGORIES = {CATEGORY_AUTOGENERATED, CATEGORY_PACKAGING}

try:
    from script.noise_normalizer import build_payload as build_noise_payload
except Exception:  # pragma: no cover - fallback for older environments without noise_normalizer.py
    build_noise_payload = None


def resolve_android_jars_path() -> str:
    explicit = os.environ.get("ANDROID_JARS_PATH")
    if explicit:
        return explicit

    sdk_root = os.environ.get("ANDROID_SDK_ROOT") or os.environ.get("ANDROID_HOME")
    if sdk_root:
        return str(Path(sdk_root) / "platforms")

    return str(Path.home() / "Library" / "Android" / "sdk" / "platforms")


ANDROID_JARS_PATH = resolve_android_jars_path()


def build_model(apk_path, output_path, return_metadata: bool = False):
    noise_report, noise_index, noise_warnings = prepare_noise_context(apk_path)
    for warning in noise_warnings:
        print("WARNING: {}".format(warning))

    cmd = "sh {script_path} {soot_path} {android_path} {apk_path} {output_path}".format(
        script_path=SH_GENERATE_DOT,
        soot_path=SOOT_JAR_PATH,
        android_path=ANDROID_JARS_PATH,
        apk_path=apk_path,
        output_path=output_path,
    )
    print("Execute command: {}".format(cmd))
    try:
        os.system(cmd)
    except Exception:
        pass
    print("Collect all .dot files")
    dots = list()
    excluded_cfg_by_category = {CATEGORY_AUTOGENERATED: 0, CATEGORY_PACKAGING: 0}
    excluded_cfg_count = 0
    library_like_cfg_count = 0
    dots_files = list(filter(lambda filename: filename.endswith(".dot"), os.listdir(output_path)))
    dots_files = sorted(dots_files)
    for filename in dots_files:
        f = os.path.join(output_path, filename)
        if os.path.isfile(f) and f.endswith(".dot"):
            noise_entry = classify_dot_by_noise(filename, noise_index)
            if noise_entry and noise_entry["category"] in EXCLUDED_NOISE_CATEGORIES:
                excluded_cfg_count += 1
                excluded_cfg_by_category[noise_entry["category"]] += 1
                continue

            dot = convert_dot_to_graph(f)
            if noise_entry:
                dot.graph["noise_category"] = noise_entry["category"]
                dot.graph["noise_reason"] = noise_entry["reason"]
                dot.graph["noise_source_path"] = noise_entry["path"]
                if noise_entry["category"] == CATEGORY_LIBRARY:
                    library_like_cfg_count += 1
            dots.append(dot)
    print("Create graphs")
    model_metadata = {
        "noise_report": noise_report,
        "noise_summary": noise_report.get("summary", {}) if isinstance(noise_report, dict) else {},
        "noise_warnings": noise_warnings,
        "total_dot_files": len(dots_files),
        "included_cfg_count": len(dots),
        "excluded_cfg_count": excluded_cfg_count,
        "excluded_cfg_by_category": excluded_cfg_by_category,
        "library_like_cfg_count": library_like_cfg_count,
    }
    if return_metadata:
        return dots, model_metadata
    return dots


def prepare_noise_context(apk_path) -> tuple:
    if build_noise_payload is None:
        return None, {}, []

    apk_file = Path(apk_path).expanduser()
    noise_warnings = []

    try:
        if apk_file.is_dir():
            noise_report = build_noise_payload(apk_file.resolve())
        elif apk_file.is_file():
            with tempfile.TemporaryDirectory(prefix="noise_normalizer_") as temp_dir:
                with zipfile.ZipFile(apk_file.resolve()) as archive:
                    archive.extractall(temp_dir)
                noise_report = build_noise_payload(Path(temp_dir))
        else:
            noise_warnings.append(
                "Noise normalization skipped because APK path does not exist: {}".format(apk_path)
            )
            return None, {}, noise_warnings
    except (FileNotFoundError, NotADirectoryError, OSError, zipfile.BadZipFile, ValueError) as exc:
        noise_warnings.append(
            "Noise normalization failed for {}: {}. Continuing with legacy feature extraction."
            .format(apk_path, exc)
        )
        return None, {}, noise_warnings

    if isinstance(noise_report, dict):
        noise_report["source_apk_path"] = str(apk_file.resolve())
    noise_warnings.extend(extract_unstable_warnings(noise_report))
    return noise_report, build_noise_index(noise_report), noise_warnings


def extract_unstable_warnings(noise_report: Optional[dict]) -> list:
    if not isinstance(noise_report, dict):
        return []

    elements = noise_report.get("elements")
    if not isinstance(elements, list):
        return []

    unstable = []
    for element in elements:
        if not isinstance(element, dict):
            continue
        if element.get("category") != CATEGORY_UNSTABLE:
            continue
        rel_path = str(element.get("path", ""))
        reason = str(element.get("reason", "unstable extraction risk"))
        unstable.append("unstable_extraction_risk for {}: {}".format(rel_path, reason))

    max_preview = 5
    if len(unstable) <= max_preview:
        return unstable
    hidden = len(unstable) - max_preview
    return unstable[:max_preview] + ["{} more unstable_extraction_risk items were detected.".format(hidden)]


def build_noise_index(noise_report: Optional[dict]) -> Dict[str, dict]:
    if not isinstance(noise_report, dict):
        return {}

    elements = noise_report.get("elements")
    if not isinstance(elements, list):
        return {}

    index: Dict[str, dict] = {}
    for element in elements:
        if not isinstance(element, dict):
            continue
        rel_path = str(element.get("path", ""))
        class_name = smali_path_to_class_name(rel_path)
        if class_name is None:
            continue

        key = normalize_class_key(class_name)
        candidate = {
            "category": str(element.get("category", "")),
            "reason": str(element.get("reason", "")),
            "path": rel_path,
        }
        existing = index.get(key)
        if existing is None or category_priority(candidate["category"]) < category_priority(existing["category"]):
            index[key] = candidate
    return index


def category_priority(category: str) -> int:
    priorities = {
        CATEGORY_AUTOGENERATED: 0,
        CATEGORY_PACKAGING: 1,
        CATEGORY_LIBRARY: 2,
        CATEGORY_UNSTABLE: 3,
    }
    return priorities.get(category, 4)


def smali_path_to_class_name(rel_path: str) -> Optional[str]:
    if not rel_path.endswith(".smali"):
        return None
    parts = rel_path.split("/")
    if len(parts) < 2:
        return None
    if not parts[0].startswith("smali"):
        return None

    class_path = "/".join(parts[1:])[:-len(".smali")]
    if not class_path:
        return None
    return class_path.replace("/", ".")


def normalize_class_key(class_name: str) -> str:
    return class_name.replace("$", ".")


def classify_dot_by_noise(filename: str, noise_index: Dict[str, dict]) -> Optional[dict]:
    if not noise_index:
        return None
    class_name = extract_dot_class_name(filename)
    return noise_index.get(normalize_class_key(class_name))


def extract_dot_class_name(filename: str) -> str:
    normalized = filename[:-4] if filename.endswith(".dot") else filename
    return normalized.split(" ", 1)[0]


def convert_dot_to_graph(dot_path):
    import pydot
    import networkx as nx
    dot = pydot.graph_from_dot_file(dot_path)[0]
    graph = nx.DiGraph()
    graph.name = "/".join(dot_path.split('/')[-2:])
    for key, value in dot.obj_dict['nodes'].items():
        if key == 'node' or key == '"\\n"':
            continue
        key = parse_key_to_int(key)
        value = value[0]['attributes']['label']
        graph.add_node(key, data=value)
    for key, value in dot.obj_dict['edges'].items():
        first = parse_key_to_int(key[0])
        second = parse_key_to_int(key[1])
        graph.add_edge(first, second)
    return graph


def parse_key_to_int(key: str) -> int:
    return int(key.replace("\"", "").replace("\'", ""))
