#!/usr/bin/env python3
"""Classify unpacked APK artifacts according to the noise normalization contract."""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from xml.etree import ElementTree

# LIB-003: optional v2 TPL detector (androguard 4.x based).
# Activated via USE_LIBRARY_V2=1 env var or build_payload(use_library_v2=True).
_USE_LIBRARY_V2_ENV: bool = os.environ.get("USE_LIBRARY_V2", "").strip() in ("1", "true", "True", "yes")


CATEGORY_LIBRARY = "library_like"
CATEGORY_AUTOGENERATED = "autogenerated_like"
CATEGORY_PACKAGING = "packaging_noise"
CATEGORY_UNSTABLE = "unstable_extraction_risk"
CATEGORY_APP = "app_specific"

SUMMARY_ORDER = (
    CATEGORY_LIBRARY,
    CATEGORY_AUTOGENERATED,
    CATEGORY_PACKAGING,
    CATEGORY_UNSTABLE,
    CATEGORY_APP,
)

KNOWN_LIBRARY_PREFIXES = (
    "android",
    "androidx",
    "com.airbnb",
    "com.bumptech",
    "com.facebook",
    "com.google",
    "com.squareup",
    "dagger",
    "io.reactivex",
    "java",
    "javax",
    "kotlin",
    "kotlinx",
    "okhttp3",
    "okio",
    "org.apache",
    "org.bouncycastle",
    "org.intellij",
    "org.jetbrains",
    "org.json",
    "retrofit2",
    "rx",
)

META_INF_SEGMENT = "META-INF"
SMALI_ROOT_RE = re.compile(r"^smali(?:_classes\d+)?$")
PRINTABLE_STRING_RE = re.compile(rb"[\x20-\x7e]{6,}")
BORING_RESOURCE_STRINGS = {
    "anim",
    "attr",
    "bool",
    "color",
    "dimen",
    "drawable",
    "id",
    "integer",
    "layout",
    "menu",
    "mipmap",
    "raw",
    "res",
    "string",
    "style",
    "styleable",
    "xml",
}


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="noise_normalizer",
        description=(
            "Scans an unpacked APK directory and labels files according to the "
            "similarity noise normalization contract."
        ),
    )
    parser.add_argument("apk_path", help="Path to an unpacked APK directory")
    parser.add_argument(
        "--output",
        help="Optional path to write the resulting JSON payload. Defaults to stdout.",
    )
    return parser.parse_args()


def ensure_input_dir(path_str: str) -> Path:
    apk_path = Path(path_str).expanduser().resolve()
    if not apk_path.exists():
        raise FileNotFoundError("APK directory does not exist: {}".format(apk_path))
    if not apk_path.is_dir():
        raise NotADirectoryError("APK path is not a directory: {}".format(apk_path))
    return apk_path


def _find_original_apk(unpacked_dir: Path) -> Optional[Path]:
    """Heuristic: look for a .apk file alongside the unpacked directory."""
    candidate = unpacked_dir.parent / (unpacked_dir.name + ".apk")
    if candidate.exists():
        return candidate
    # Also check if parent itself contains a .apk with same stem
    for p in unpacked_dir.parent.glob("*.apk"):
        if p.stem == unpacked_dir.name:
            return p
    return None


def build_payload(
    apk_path: Path,
    use_library_v2: Optional[bool] = None,
) -> Dict[str, object]:
    """Build classification payload for an unpacked APK directory.

    Args:
        apk_path: Path to unpacked APK directory.
        use_library_v2: If True, use v2 TPL detector (androguard 4.x).
                        If None, falls back to USE_LIBRARY_V2 env var.
                        If False or androguard unavailable, uses v1 prefix-match.
    """
    elements: List[Dict[str, str]] = []
    summary = {category: 0 for category in SUMMARY_ORDER}

    # LIB-003: pre-compute v2 detections once per APK
    _use_v2 = use_library_v2 if use_library_v2 is not None else _USE_LIBRARY_V2_ENV
    apk_packages: Optional[frozenset] = None
    tpl_detections: Optional[Dict] = None
    if _use_v2:
        try:
            from library_view_v2 import (  # type: ignore[import]
                detect_tpl_in_packages,
                extract_apk_packages,
            )
            original_apk = _find_original_apk(apk_path)
            if original_apk is not None:
                apk_packages = extract_apk_packages(
                    str(original_apk),
                    cache_dir=str(apk_path),
                )
                tpl_detections = detect_tpl_in_packages(apk_packages)
        except Exception:
            pass  # graceful fallback to v1

    for file_path in iter_files(apk_path):
        rel_path = file_path.relative_to(apk_path).as_posix()
        category, reason = classify_file(
            file_path,
            rel_path,
            apk_packages=apk_packages,
            tpl_detections=tpl_detections,
        )
        elements.append(
            {
                "path": rel_path,
                "category": category,
                "reason": reason,
            }
        )
        summary[category] += 1

    return {
        "apk_path": str(apk_path),
        "timestamp": utc_timestamp(),
        "elements": elements,
        "summary": summary,
    }


def iter_files(apk_path: Path) -> Iterable[Path]:
    for path in sorted(apk_path.rglob("*")):
        if path.is_file():
            yield path


def classify_file(
    file_path: Path,
    rel_path: str,
    apk_packages: Optional[frozenset] = None,
    tpl_detections: Optional[Dict] = None,
) -> Tuple[str, str]:
    unstable = detect_unstable_extraction_risk(file_path, rel_path)
    if unstable is not None:
        return unstable

    packaging = detect_packaging_noise(file_path, rel_path)
    if packaging is not None:
        return packaging

    autogenerated = detect_autogenerated_like(rel_path)
    if autogenerated is not None:
        return autogenerated

    # LIB-003: use v2 detector if packages are available
    if apk_packages is not None:
        try:
            from library_view_v2 import detect_library_like_v2  # type: ignore[import]
            library = detect_library_like_v2(
                rel_path,
                apk_packages=apk_packages,
                tpl_detections=tpl_detections,
            )
        except ImportError:
            library = detect_library_like(rel_path)
    else:
        library = detect_library_like(rel_path)

    if library is not None:
        return library

    return CATEGORY_APP, default_reason(rel_path)


def detect_unstable_extraction_risk(file_path: Path, rel_path: str) -> Optional[Tuple[str, str]]:
    if is_smali_file(rel_path):
        try:
            content = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return CATEGORY_UNSTABLE, "smali file is not valid UTF-8 after extraction"
        if not content.strip():
            return CATEGORY_UNSTABLE, "empty smali file"

    if rel_path.endswith(".xml"):
        try:
            ElementTree.parse(file_path)
        except (ElementTree.ParseError, UnicodeDecodeError, ValueError):
            return CATEGORY_UNSTABLE, "XML parsing failed"

    return None


def detect_packaging_noise(file_path: Path, rel_path: str) -> Optional[Tuple[str, str]]:
    parts = rel_path.split("/")
    filename = parts[-1]
    lowercase_name = filename.lower()

    if META_INF_SEGMENT in parts:
        return CATEGORY_PACKAGING, "packaging artifact under META-INF"

    if lowercase_name.endswith(".rsa"):
        return CATEGORY_PACKAGING, "APK signing artifact (*.RSA)"

    if lowercase_name.endswith(".sf"):
        return CATEGORY_PACKAGING, "APK signing artifact (*.SF)"

    if lowercase_name.endswith(".mf"):
        return CATEGORY_PACKAGING, "APK manifest digest artifact (*.MF)"

    if rel_path == "resources.arsc":
        if has_meaningful_arsc_strings(file_path):
            return CATEGORY_APP, "resources.arsc contains meaningful extracted strings"
        return CATEGORY_PACKAGING, "resources.arsc without meaningful strings"

    return None


def detect_autogenerated_like(rel_path: str) -> Optional[Tuple[str, str]]:
    filename = rel_path.rsplit("/", 1)[-1]

    if filename == "BuildConfig.smali":
        return CATEGORY_AUTOGENERATED, "autogenerated BuildConfig.smali"

    if filename == "R.smali" or filename.startswith("R$"):
        return CATEGORY_AUTOGENERATED, "autogenerated Android resource accessor"

    if "$$Lambda" in filename or "$$ExternalSyntheticLambda" in filename:
        return CATEGORY_AUTOGENERATED, "compiler-generated lambda wrapper"

    return None


def detect_library_like(rel_path: str) -> Optional[Tuple[str, str]]:
    package_path = extract_package_path(rel_path)
    if package_path is None:
        return None

    package_dotted = package_path.replace("/", ".")
    for prefix in KNOWN_LIBRARY_PREFIXES:
        prefix_slash = prefix.replace(".", "/")
        if package_path == prefix_slash or package_path.startswith(prefix_slash + "/"):
            return CATEGORY_LIBRARY, "known library prefix {}".format(prefix)

    if package_dotted.startswith("android.support."):
        return CATEGORY_LIBRARY, "known library prefix android.support"

    return None


def extract_package_path(rel_path: str) -> Optional[str]:
    parts = rel_path.split("/")
    if not parts:
        return None

    if SMALI_ROOT_RE.match(parts[0]):
        if len(parts) < 3:
            return None
        return "/".join(parts[1:-1])

    if rel_path == "AndroidManifest.xml":
        return None

    if parts[0] in {"res", "assets", "lib", "kotlin"}:
        return None

    if len(parts) > 1:
        return "/".join(parts[:-1])

    return None


def is_smali_file(rel_path: str) -> bool:
    parts = rel_path.split("/")
    return bool(parts and SMALI_ROOT_RE.match(parts[0]) and rel_path.endswith(".smali"))


def has_meaningful_arsc_strings(file_path: Path) -> bool:
    try:
        blob = file_path.read_bytes()
    except OSError:
        return False

    for raw_match in PRINTABLE_STRING_RE.findall(blob):
        text = raw_match.decode("ascii", errors="ignore").strip()
        lower = text.lower()
        if lower in BORING_RESOURCE_STRINGS:
            continue
        if len(text) < 8:
            continue
        if sum(1 for ch in text if ch.isalpha()) < 3:
            continue
        if "." in text or "/" in text or "_" in text or len(text) >= 12:
            return True
    return False


def default_reason(rel_path: str) -> str:
    if rel_path == "AndroidManifest.xml":
        return "manifest kept as app-specific metadata"
    if rel_path.startswith("res/"):
        return "resource file not matched by noise heuristics"
    if rel_path.startswith("assets/"):
        return "asset file not matched by noise heuristics"
    if is_smali_file(rel_path):
        return "smali file outside library/autogenerated heuristics"
    return "file not matched by noise heuristics"


def write_output(payload: Dict[str, object], output_path: Optional[str]) -> None:
    payload_json = json.dumps(payload, indent=2, ensure_ascii=False)
    if output_path:
        target = Path(output_path).expanduser().resolve()
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(payload_json + os.linesep, encoding="utf-8")
        return
    print(payload_json)


def main() -> int:
    args = parse_args()
    try:
        apk_path = ensure_input_dir(args.apk_path)
        payload = build_payload(apk_path)
        write_output(payload, args.output)
    except (FileNotFoundError, NotADirectoryError, OSError) as exc:
        raise SystemExit(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
