#!/usr/bin/env python3
"""Run an A/B study for pairwise similarity with and without noise cleanup."""

import argparse
import io
import json
import os
import sys
import tempfile
from collections import defaultdict
from contextlib import contextmanager, redirect_stdout
from dataclasses import dataclass, field
from datetime import datetime, timezone
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
PHD_ROOT = PROJECT_ROOT.parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    from script.calculate_apks_similarity.build_comparison_matrix import calculate_similarity_two_dots
    from script.calculate_apks_similarity.build_model import build_model, convert_dot_to_graph
    from script.calculate_apks_similarity.calculate_models_similarity import calculate_models_similarity
    from script.calculate_apks_similarity.result_contract import extract_class_name
    from script.noise_normalizer import (
        CATEGORY_APP,
        CATEGORY_AUTOGENERATED,
        CATEGORY_LIBRARY,
        CATEGORY_PACKAGING,
        CATEGORY_UNSTABLE,
        KNOWN_LIBRARY_PREFIXES,
        SUMMARY_ORDER,
        build_payload as build_noise_payload,
    )
except ImportError:
    sys.path.insert(0, str(SCRIPT_DIR))
    from calculate_apks_similarity.build_comparison_matrix import calculate_similarity_two_dots
    from calculate_apks_similarity.build_model import build_model, convert_dot_to_graph
    from calculate_apks_similarity.calculate_models_similarity import calculate_models_similarity
    from calculate_apks_similarity.result_contract import extract_class_name
    from noise_normalizer import (
        CATEGORY_APP,
        CATEGORY_AUTOGENERATED,
        CATEGORY_LIBRARY,
        CATEGORY_PACKAGING,
        CATEGORY_UNSTABLE,
        KNOWN_LIBRARY_PREFIXES,
        SUMMARY_ORDER,
        build_payload as build_noise_payload,
    )


PAIR_CONTAINER_KEYS = (
    "pairs",
    "pairwise",
    "results",
    "candidates",
    "candidate_list",
    "items",
    "data",
)
PAIR_SEPARATORS = ("::", "__", "|")
GRAPH_RELEVANT_CATEGORIES = (CATEGORY_LIBRARY, CATEGORY_AUTOGENERATED, CATEGORY_UNSTABLE)
DEFAULT_INS_BLOCK_SIM_THRESHOLD = 0.80
DEFAULT_GED_TIMEOUT_SEC = 30
DEFAULT_PROCESSES_COUNT = 1
DEFAULT_THREADS_COUNT = 2


@dataclass
class AppRecord:
    app_id: str
    root_path: Path
    unpacked_dir: Optional[Path] = None
    code_dir: Optional[Path] = None
    apk_path: Optional[Path] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)


@dataclass
class AppAnalysis:
    app_id: str
    source_mode: str
    full_graphs: List[Any]
    filtered_graphs: List[Any]
    full_graph_tokens: List[str]
    filtered_graph_tokens: List[str]
    noise_source: str
    noise_payload: Dict[str, Any]
    noise_elements_by_category: Dict[str, int]
    graphs_filtered_by_category: Dict[str, int]
    warnings: List[str] = field(default_factory=list)


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="noise_ablation_study",
        description=(
            "Compare pairwise APK similarity with and without noise cleanup "
            "and generate a JSON + human-readable report."
        ),
    )
    parser.add_argument(
        "--apk-dir",
        default="",
        help=(
            "Root directory containing app entries. Each entry may be an unpacked APK "
            "directory, a representation bundle with code/*.dot, or an APK file."
        ),
    )
    parser.add_argument(
        "--pairs",
        default="",
        help="Optional JSON file with candidate pairs. If omitted, all pairs are generated.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to the JSON report that will be generated.",
    )
    parser.add_argument(
        "--synthetic",
        action="store_true",
        help="Run a fully synthetic ablation study without real APK artifacts.",
    )
    parser.add_argument("--ins-block-sim-threshold", type=float, default=DEFAULT_INS_BLOCK_SIM_THRESHOLD)
    parser.add_argument("--ged-timeout-sec", type=int, default=DEFAULT_GED_TIMEOUT_SEC)
    parser.add_argument("--processes-count", type=int, default=DEFAULT_PROCESSES_COUNT)
    parser.add_argument("--threads-count", type=int, default=DEFAULT_THREADS_COUNT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_path = Path(args.output).expanduser().resolve()
    apk_root = Path(args.apk_dir).expanduser().resolve() if args.apk_dir else None
    pairs_payload = None
    if args.pairs:
        pairs_payload = load_pairs_payload(Path(args.pairs).expanduser().resolve())

    report = run_ablation_study(
        apk_root=apk_root,
        output_path=output_path,
        pairs_payload=pairs_payload,
        synthetic=args.synthetic,
        ins_block_sim_threshold=args.ins_block_sim_threshold,
        ged_timeout_sec=args.ged_timeout_sec,
        processes_count=args.processes_count,
        threads_count=args.threads_count,
    )
    print(report["human_summary"])
    return 0


def run_ablation_study(
    apk_root: Optional[Path],
    output_path: Optional[Path],
    pairs_payload: Optional[Any] = None,
    synthetic: bool = False,
    ins_block_sim_threshold: float = DEFAULT_INS_BLOCK_SIM_THRESHOLD,
    ged_timeout_sec: int = DEFAULT_GED_TIMEOUT_SEC,
    processes_count: int = DEFAULT_PROCESSES_COUNT,
    threads_count: int = DEFAULT_THREADS_COUNT,
) -> Dict[str, Any]:
    if synthetic:
        app_analyses = build_synthetic_app_analyses()
        pair_specs = resolve_pairs_from_payload(pairs_payload, list(app_analyses.keys()))
        if not pair_specs:
            pair_specs = generate_all_pairs(list(app_analyses.keys()))
        pair_results = evaluate_synthetic_pairs(app_analyses, pair_specs)
        return finalize_report(
            mode="synthetic",
            apk_root=apk_root,
            output_path=output_path,
            pair_results=pair_results,
            app_analyses=app_analyses,
            warnings=[],
        )

    if apk_root is None:
        raise ValueError("--apk-dir is required unless --synthetic is enabled.")
    if not apk_root.exists():
        raise FileNotFoundError("APK directory does not exist: {}".format(apk_root))
    if not apk_root.is_dir():
        raise NotADirectoryError("APK root is not a directory: {}".format(apk_root))

    app_records = discover_apps(apk_root)
    if len(app_records) < 2:
        raise ValueError("At least two app entries are required under {}".format(apk_root))

    pair_specs = resolve_pairs_from_payload(pairs_payload, list(app_records.keys()))
    if not pair_specs:
        pair_specs = generate_all_pairs(list(app_records.keys()))
    if not pair_specs:
        raise ValueError("Could not construct any pairs to evaluate.")

    app_analyses, warnings = analyze_real_apps(app_records)
    pair_results = evaluate_real_pairs(
        app_analyses=app_analyses,
        pair_specs=pair_specs,
        ins_block_sim_threshold=ins_block_sim_threshold,
        ged_timeout_sec=ged_timeout_sec,
        processes_count=processes_count,
        threads_count=threads_count,
    )
    return finalize_report(
        mode="real",
        apk_root=apk_root,
        output_path=output_path,
        pair_results=pair_results,
        app_analyses=app_analyses,
        warnings=warnings,
    )


def load_pairs_payload(path: Path) -> Any:
    if not path.exists():
        raise FileNotFoundError("Pairs file does not exist: {}".format(path))
    return json.loads(path.read_text(encoding="utf-8"))


def ensure_pair_items(payload: Any) -> List[Any]:
    if payload is None:
        return []
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for key in PAIR_CONTAINER_KEYS:
            value = payload.get(key)
            if isinstance(value, list):
                return value
        if looks_like_pair(payload):
            return [payload]
    raise ValueError("Pairs payload must be a pair object, an array, or an object with a pair list.")


def looks_like_pair(item: Dict[str, Any]) -> bool:
    if any(key in item for key in ("pair_id", "pair_key", "app_a", "app_b", "query_app_id", "candidate_app_id")):
        return True
    apps = item.get("apps")
    return isinstance(apps, dict) and ("app_a" in apps and "app_b" in apps)


def resolve_pairs_from_payload(payload: Any, available_ids: Sequence[str]) -> List[Dict[str, str]]:
    if payload is None:
        return []

    items = ensure_pair_items(payload)
    resolved = []
    seen = set()
    for index, item in enumerate(items):
        pair_id, app_a, app_b = resolve_single_pair(item, available_ids, index)
        if app_a == app_b:
            continue
        key = tuple(sorted([app_a, app_b]))
        if key in seen:
            continue
        seen.add(key)
        resolved.append({"pair": pair_id or "{}__{}".format(app_a, app_b), "app_a": app_a, "app_b": app_b})
    return resolved


def resolve_single_pair(item: Any, available_ids: Sequence[str], index: int) -> Tuple[str, str, str]:
    if isinstance(item, str):
        for separator in PAIR_SEPARATORS:
            if separator in item:
                raw_a, raw_b = item.split(separator, 1)
                app_a = resolve_app_ref(raw_a, available_ids)
                app_b = resolve_app_ref(raw_b, available_ids)
                return item, app_a, app_b
        raise ValueError("Unsupported string pair format at index {}: {!r}".format(index, item))

    if not isinstance(item, dict):
        raise ValueError("Pair item at index {} must be an object or a string.".format(index))

    pair_id = first_present(item, ("pair_id", "pair_key", "id"))
    apps = item.get("apps")
    app_a_raw = first_present(item, ("app_a", "query_app_id", "query_app", "apk_1", "app_1"))
    app_b_raw = first_present(item, ("app_b", "candidate_app_id", "candidate_app", "apk_2", "app_2"))
    if isinstance(apps, dict):
        app_a_raw = app_a_raw or first_present(apps, ("app_a", "query_app"))
        app_b_raw = app_b_raw or first_present(apps, ("app_b", "candidate_app"))
    if app_a_raw is None or app_b_raw is None:
        raise ValueError("Could not resolve app_a/app_b in pair item at index {}.".format(index))
    app_a = resolve_app_ref(app_a_raw, available_ids)
    app_b = resolve_app_ref(app_b_raw, available_ids)
    if not pair_id:
        pair_id = "{}__{}".format(app_a, app_b)
    return str(pair_id), app_a, app_b


def first_present(mapping: Dict[str, Any], keys: Sequence[str]) -> Any:
    for key in keys:
        if key in mapping:
            return mapping[key]
    return None


def resolve_app_ref(raw_value: Any, available_ids: Sequence[str]) -> str:
    if isinstance(raw_value, dict):
        raw_value = first_present(raw_value, ("app_id", "id", "name", "apk_path", "path"))
    if raw_value is None:
        raise ValueError("App reference is missing.")
    candidate = str(raw_value).strip()
    if not candidate:
        raise ValueError("App reference is empty.")
    if candidate in available_ids:
        return candidate

    candidate_path = Path(candidate)
    candidate_name = candidate_path.name
    candidate_stem = candidate_path.stem
    for app_id in available_ids:
        if candidate_name == app_id or candidate_stem == app_id:
            return app_id
    raise ValueError(
        "Unknown app reference {!r}. Available app ids: {}".format(candidate, ", ".join(sorted(available_ids)))
    )


def generate_all_pairs(app_ids: Sequence[str]) -> List[Dict[str, str]]:
    result = []
    for app_a, app_b in combinations(sorted(app_ids), 2):
        result.append({"pair": "{}__{}".format(app_a, app_b), "app_a": app_a, "app_b": app_b})
    return result


def discover_apps(apk_root: Path) -> Dict[str, AppRecord]:
    records = {}
    for child in sorted(apk_root.iterdir(), key=lambda path: path.name):
        record = inspect_app_entry(child, apk_root)
        if record is None:
            continue
        if record.app_id in records:
            raise ValueError("Duplicate app_id discovered: {!r}".format(record.app_id))
        records[record.app_id] = record
    return records


def inspect_app_entry(path: Path, apk_root: Path) -> Optional[AppRecord]:
    if path.name.startswith("."):
        return None

    if path.is_file() and path.suffix.lower() == ".apk":
        return AppRecord(app_id=path.stem, root_path=path, apk_path=path)

    if not path.is_dir():
        return None

    metadata = load_optional_json(path / "metadata.json")
    app_id = str(metadata.get("app_id") or path.name)
    code_dir = find_code_dir(path, metadata)
    unpacked_dir = find_unpacked_dir(path)
    apk_path = find_apk_path(path, metadata, apk_root)
    warnings = []

    if code_dir is None and apk_path is None and unpacked_dir is None:
        return None
    if unpacked_dir is None:
        warnings.append(
            "No unpacked APK directory discovered for {}; cleanup will use graph-name heuristics only.".format(app_id)
        )

    return AppRecord(
        app_id=app_id,
        root_path=path,
        unpacked_dir=unpacked_dir,
        code_dir=code_dir,
        apk_path=apk_path,
        metadata=metadata,
        warnings=warnings,
    )


def load_optional_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return payload if isinstance(payload, dict) else {}


def resolve_maybe_relative(path_str: str, extra_bases: Sequence[Path]) -> Optional[Path]:
    candidate = Path(path_str).expanduser()
    if candidate.is_absolute() and candidate.exists():
        return candidate.resolve()

    bases = list(extra_bases) + [PROJECT_ROOT, PHD_ROOT, PROJECT_ROOT.parent]
    for base in bases:
        resolved = (base / candidate).resolve()
        if resolved.exists():
            return resolved
    return candidate.resolve() if candidate.is_absolute() else None


def find_code_dir(entry: Path, metadata: Dict[str, Any]) -> Optional[Path]:
    direct = entry / "code"
    if direct.is_dir() and any(child.suffix == ".dot" for child in direct.iterdir()):
        return direct.resolve()

    if entry.is_dir() and any(child.suffix == ".dot" for child in entry.iterdir()):
        return entry.resolve()

    artifacts = metadata.get("artifacts")
    if isinstance(artifacts, dict):
        code_dir_value = artifacts.get("code_dir")
        if isinstance(code_dir_value, str) and code_dir_value:
            resolved = resolve_maybe_relative(code_dir_value, [entry])
            if resolved is not None and resolved.is_dir():
                return resolved
    return None


def find_unpacked_dir(entry: Path) -> Optional[Path]:
    if looks_like_unpacked_dir(entry):
        return entry.resolve()
    if not entry.is_dir():
        return None
    for child in sorted(entry.iterdir(), key=lambda path: path.name):
        if child.is_dir() and looks_like_unpacked_dir(child):
            return child.resolve()
    return None


def looks_like_unpacked_dir(path: Path) -> bool:
    if not path.is_dir():
        return False
    if (path / "AndroidManifest.xml").exists():
        return True
    child_names = {child.name for child in path.iterdir()}
    if any(name.startswith("smali") for name in child_names):
        return True
    return bool({"META-INF", "res", "assets", "lib"} & child_names)


def find_apk_path(entry: Path, metadata: Dict[str, Any], apk_root: Path) -> Optional[Path]:
    for key in ("resolved_apk_path", "apk_path"):
        value = metadata.get(key)
        if isinstance(value, str) and value:
            resolved = resolve_maybe_relative(value, [entry, apk_root])
            if resolved is not None and resolved.is_file():
                return resolved

    if entry.is_file() and entry.suffix.lower() == ".apk":
        return entry.resolve()

    if entry.is_dir():
        apk_children = sorted(child for child in entry.iterdir() if child.is_file() and child.suffix.lower() == ".apk")
        if len(apk_children) == 1:
            return apk_children[0].resolve()

        sibling_apks = sorted(
            child
            for child in entry.parent.iterdir()
            if child.is_file() and child.suffix.lower() == ".apk" and child.stem == entry.name
        )
        if sibling_apks:
            return sibling_apks[0].resolve()
    return None


def analyze_real_apps(app_records: Dict[str, AppRecord]) -> Tuple[Dict[str, AppAnalysis], List[str]]:
    analyses = {}
    warnings = []
    for app_id in sorted(app_records):
        app_record = app_records[app_id]
        analysis = analyze_single_real_app(app_record)
        analyses[app_id] = analysis
        warnings.extend(analysis.warnings)
    return analyses, unique_strings(warnings)


def analyze_single_real_app(app_record: AppRecord) -> AppAnalysis:
    full_graphs = load_graphs_for_app(app_record)
    noise_source = "noise_normalizer" if app_record.unpacked_dir is not None else "graph_name_heuristics"
    if app_record.unpacked_dir is not None:
        noise_payload = build_noise_payload(app_record.unpacked_dir)
        noise_elements_by_category = normalize_category_counts(noise_payload.get("summary", {}))
    else:
        noise_payload, noise_elements_by_category = build_graph_heuristic_noise_payload(full_graphs)

    classes_by_category = build_filtered_class_index(noise_payload, full_graphs)
    filtered_graphs, graphs_filtered_by_category = filter_graphs(full_graphs, classes_by_category)
    warnings = list(app_record.warnings)
    if app_record.unpacked_dir is not None and app_record.apk_path is None and app_record.code_dir is None:
        warnings.append(
            "App {} has an unpacked directory but no neighboring APK or code/*.dot fallback.".format(app_record.app_id)
        )

    return AppAnalysis(
        app_id=app_record.app_id,
        source_mode="real",
        full_graphs=full_graphs,
        filtered_graphs=filtered_graphs,
        full_graph_tokens=[],
        filtered_graph_tokens=[],
        noise_source=noise_source,
        noise_payload=noise_payload,
        noise_elements_by_category=noise_elements_by_category,
        graphs_filtered_by_category=graphs_filtered_by_category,
        warnings=warnings,
    )


def load_graphs_for_app(app_record: AppRecord) -> List[Any]:
    if app_record.code_dir is not None:
        return load_graphs_from_dot_dir(app_record.code_dir)

    if app_record.apk_path is not None:
        with tempfile.TemporaryDirectory(prefix="noise_ablation_graphs_") as tmp_dir:
            with working_directory(PROJECT_ROOT):
                return build_model(str(app_record.apk_path), tmp_dir)

    if app_record.unpacked_dir is not None:
        with tempfile.TemporaryDirectory(prefix="noise_ablation_graphs_") as tmp_dir:
            with working_directory(PROJECT_ROOT):
                graphs = build_model(str(app_record.unpacked_dir), tmp_dir)
            if graphs:
                return graphs
    raise FileNotFoundError(
        "Could not build graphs for {}. Provide code/*.dot, a neighboring APK, or an unpacked directory "
        "supported by build_model.".format(app_record.app_id)
    )


def load_graphs_from_dot_dir(dot_dir: Path) -> List[Any]:
    graphs = []
    for dot_path in sorted(dot_dir.glob("*.dot"), key=lambda path: path.name):
        graphs.append(convert_dot_to_graph(str(dot_path)))
    return graphs


def normalize_category_counts(summary: Dict[str, Any]) -> Dict[str, int]:
    result = {category: 0 for category in SUMMARY_ORDER}
    for category in SUMMARY_ORDER:
        raw_value = summary.get(category, 0)
        try:
            result[category] = int(raw_value)
        except (TypeError, ValueError):
            result[category] = 0
    return result


def build_graph_heuristic_noise_payload(graphs: List[Any]) -> Tuple[Dict[str, Any], Dict[str, int]]:
    elements = []
    summary = {category: 0 for category in SUMMARY_ORDER}
    for graph in graphs:
        class_name = extract_class_name(graph.name)
        category = classify_graph_class(class_name)
        if category == CATEGORY_APP:
            continue
        elements.append(
            {
                "path": "graph://{}".format(graph.name),
                "category": category,
                "reason": "graph-name heuristic classification for {}".format(class_name),
            }
        )
        summary[category] += 1
    payload = {
        "apk_path": None,
        "timestamp": utc_timestamp(),
        "elements": elements,
        "summary": summary,
    }
    return payload, summary


def build_filtered_class_index(noise_payload: Dict[str, Any], graphs: List[Any]) -> Dict[str, set]:
    result = {category: set() for category in SUMMARY_ORDER}
    for element in noise_payload.get("elements", []):
        if not isinstance(element, dict):
            continue
        category = str(element.get("category") or "").strip()
        if category not in result or category == CATEGORY_APP:
            continue

        path_value = str(element.get("path") or "")
        class_name = class_name_from_noise_path(path_value)
        if class_name is not None:
            result[category].add(class_name)

    if all(not result[category] for category in GRAPH_RELEVANT_CATEGORIES):
        for graph in graphs:
            class_name = extract_class_name(graph.name)
            category = classify_graph_class(class_name)
            if category in GRAPH_RELEVANT_CATEGORIES:
                result[category].add(class_name)
    return result


def class_name_from_noise_path(path_value: str) -> Optional[str]:
    if not path_value:
        return None
    if path_value.startswith("graph://"):
        return extract_class_name(path_value[len("graph://") :])

    parts = path_value.split("/")
    if not parts:
        return None
    if not parts[0].startswith("smali") or not path_value.endswith(".smali") or len(parts) < 2:
        return None
    rel_parts = parts[1:]
    class_path = "/".join(rel_parts)
    if not class_path.endswith(".smali"):
        return None
    return class_path[:-6].replace("/", ".")


def classify_graph_class(class_name: str) -> str:
    if is_autogenerated_class(class_name):
        return CATEGORY_AUTOGENERATED
    if is_library_class(class_name):
        return CATEGORY_LIBRARY
    return CATEGORY_APP


def is_autogenerated_class(class_name: str) -> bool:
    if class_name.endswith(".BuildConfig") or class_name.endswith("$BuildConfig"):
        return True
    if class_name.endswith(".R") or class_name.endswith("$R"):
        return True
    if ".R." in class_name or "$R$" in class_name:
        return True
    return "$$Lambda" in class_name or "$$ExternalSyntheticLambda" in class_name


def is_library_class(class_name: str) -> bool:
    if class_name.startswith("android.support."):
        return True
    for prefix in KNOWN_LIBRARY_PREFIXES:
        if class_name == prefix or class_name.startswith(prefix + "."):
            return True
    return False


def filter_graphs(graphs: List[Any], classes_by_category: Dict[str, set]) -> Tuple[List[Any], Dict[str, int]]:
    filtered = []
    removed_by_category = {category: 0 for category in SUMMARY_ORDER}
    all_filtered_classes = {}
    for category, values in classes_by_category.items():
        for value in values:
            all_filtered_classes[value] = category

    for graph in graphs:
        class_name = extract_class_name(graph.name)
        category = all_filtered_classes.get(class_name)
        if category in GRAPH_RELEVANT_CATEGORIES:
            removed_by_category[category] += 1
            continue
        filtered.append(graph)
    return filtered, removed_by_category


def evaluate_real_pairs(
    app_analyses: Dict[str, AppAnalysis],
    pair_specs: Sequence[Dict[str, str]],
    ins_block_sim_threshold: float,
    ged_timeout_sec: int,
    processes_count: int,
    threads_count: int,
) -> List[Dict[str, Any]]:
    results = []
    for pair_spec in pair_specs:
        analysis_a = app_analyses[pair_spec["app_a"]]
        analysis_b = app_analyses[pair_spec["app_b"]]
        score_without = score_real_graphs(
            analysis_a.full_graphs,
            analysis_b.full_graphs,
            ins_block_sim_threshold=ins_block_sim_threshold,
            ged_timeout_sec=ged_timeout_sec,
            processes_count=processes_count,
            threads_count=threads_count,
        )
        score_with = score_real_graphs(
            analysis_a.filtered_graphs,
            analysis_b.filtered_graphs,
            ins_block_sim_threshold=ins_block_sim_threshold,
            ged_timeout_sec=ged_timeout_sec,
            processes_count=processes_count,
            threads_count=threads_count,
        )
        results.append(
            build_pair_result(
                pair_id=pair_spec["pair"],
                app_a=analysis_a,
                app_b=analysis_b,
                score_with=score_with,
                score_without=score_without,
            )
        )
    return results


def score_real_graphs(
    graphs_a: List[Any],
    graphs_b: List[Any],
    ins_block_sim_threshold: float,
    ged_timeout_sec: int,
    processes_count: int,
    threads_count: int,
) -> float:
    if not graphs_a or not graphs_b:
        return 0.0
    matrix = build_similarity_matrix(
        graphs_a,
        graphs_b,
        ins_block_sim_threshold=ins_block_sim_threshold,
        ged_timeout_sec=ged_timeout_sec,
        processes_count=processes_count,
        threads_count=threads_count,
    )
    similarity_score, _ = calculate_models_similarity(matrix, graphs_a, graphs_b)
    return float(similarity_score)


def build_similarity_matrix(
    graphs_a: List[Any],
    graphs_b: List[Any],
    ins_block_sim_threshold: float,
    ged_timeout_sec: int,
    processes_count: int,
    threads_count: int,
) -> np.ndarray:
    max_workers = max(1, int(processes_count) * int(threads_count))
    rows = []
    if max_workers == 1:
        for graph_a in graphs_a:
            row = []
            for graph_b in graphs_b:
                row.append(
                    score_single_graph_pair(
                        graph_a,
                        graph_b,
                        ins_block_sim_threshold=ins_block_sim_threshold,
                        ged_timeout_sec=ged_timeout_sec,
                    )
                )
            rows.append(row)
        return np.array(rows, dtype=float)

    from concurrent.futures import ThreadPoolExecutor

    tasks = []
    positions = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        for row_index, graph_a in enumerate(graphs_a):
            for col_index, graph_b in enumerate(graphs_b):
                positions.append((row_index, col_index))
                tasks.append(
                    executor.submit(
                        score_single_graph_pair,
                        graph_a,
                        graph_b,
                        ins_block_sim_threshold=ins_block_sim_threshold,
                        ged_timeout_sec=ged_timeout_sec,
                    )
                )

    matrix = np.zeros((len(graphs_a), len(graphs_b)), dtype=float)
    for (row_index, col_index), task in zip(positions, tasks):
        matrix[row_index, col_index] = task.result()
    return matrix


def score_single_graph_pair(
    graph_a: Any,
    graph_b: Any,
    ins_block_sim_threshold: float,
    ged_timeout_sec: int,
) -> float:
    try:
        with redirect_stdout(io.StringIO()):
            similarity_score = calculate_similarity_two_dots(
                graph_a,
                graph_b,
                ins_block_sim_threshold=ins_block_sim_threshold,
                ged_timeout_sec=ged_timeout_sec,
            )
    except TypeError:
        return 0.0
    except Exception:
        return 0.0
    if similarity_score is None:
        return 0.0
    return max(0.0, min(1.0, float(similarity_score)))


def build_pair_result(
    pair_id: str,
    app_a: AppAnalysis,
    app_b: AppAnalysis,
    score_with: float,
    score_without: float,
) -> Dict[str, Any]:
    noise_by_category = {}
    for category in SUMMARY_ORDER:
        noise_by_category[category] = {
            "noise_elements": int(app_a.noise_elements_by_category.get(category, 0))
            + int(app_b.noise_elements_by_category.get(category, 0)),
            "graphs_filtered": int(app_a.graphs_filtered_by_category.get(category, 0))
            + int(app_b.graphs_filtered_by_category.get(category, 0)),
        }

    total_noise_elements = sum(item["noise_elements"] for item in noise_by_category.values() if item["noise_elements"] > 0)
    total_graphs_filtered = sum(item["graphs_filtered"] for item in noise_by_category.values() if item["graphs_filtered"] > 0)
    return {
        "pair": pair_id,
        "app_a": app_a.app_id,
        "app_b": app_b.app_id,
        "score_with": round(float(score_with), 6),
        "score_without": round(float(score_without), 6),
        "delta": round(float(score_with) - float(score_without), 6),
        "noise_elements_filtered": int(total_noise_elements),
        "graphs_filtered": int(total_graphs_filtered),
        "graphs_used_with": {
            "app_a": len(app_a.filtered_graphs),
            "app_b": len(app_b.filtered_graphs),
        },
        "graphs_used_without": {
            "app_a": len(app_a.full_graphs),
            "app_b": len(app_b.full_graphs),
        },
        "noise_sources": {
            "app_a": app_a.noise_source,
            "app_b": app_b.noise_source,
        },
        "noise_by_category": noise_by_category,
        "warnings": unique_strings(app_a.warnings + app_b.warnings),
    }


def build_synthetic_app_analyses() -> Dict[str, AppAnalysis]:
    specs = {
        "synthetic-alpha": {
            "full": [
                "app:checkout_flow",
                "app:auth_flow",
                "lib:shared_ui",
                "lib:shared_net",
                "auto:BuildConfig",
                "auto:R",
                "auto:Lambda",
            ],
            "filtered": ["app:checkout_flow", "app:auth_flow"],
            "noise": {
                CATEGORY_LIBRARY: {"noise_elements": 2, "graphs_filtered": 2},
                CATEGORY_AUTOGENERATED: {"noise_elements": 3, "graphs_filtered": 3},
                CATEGORY_PACKAGING: {"noise_elements": 2, "graphs_filtered": 0},
                CATEGORY_UNSTABLE: {"noise_elements": 0, "graphs_filtered": 0},
            },
        },
        "synthetic-beta": {
            "full": [
                "app:checkout_flow",
                "app:auth_flow",
                "lib:shared_ui",
                "auto:BuildConfig",
                "auto:R",
            ],
            "filtered": ["app:checkout_flow", "app:auth_flow"],
            "noise": {
                CATEGORY_LIBRARY: {"noise_elements": 1, "graphs_filtered": 1},
                CATEGORY_AUTOGENERATED: {"noise_elements": 2, "graphs_filtered": 2},
                CATEGORY_PACKAGING: {"noise_elements": 1, "graphs_filtered": 0},
                CATEGORY_UNSTABLE: {"noise_elements": 0, "graphs_filtered": 0},
            },
        },
        "synthetic-gamma": {
            "full": [
                "app:ad_flow",
                "app:tracking_flow",
                "lib:shared_ui",
                "lib:shared_net",
                "auto:BuildConfig",
                "auto:R",
                "auto:Lambda",
            ],
            "filtered": ["app:ad_flow", "app:tracking_flow"],
            "noise": {
                CATEGORY_LIBRARY: {"noise_elements": 2, "graphs_filtered": 2},
                CATEGORY_AUTOGENERATED: {"noise_elements": 3, "graphs_filtered": 3},
                CATEGORY_PACKAGING: {"noise_elements": 3, "graphs_filtered": 0},
                CATEGORY_UNSTABLE: {"noise_elements": 1, "graphs_filtered": 0},
            },
        },
    }

    analyses = {}
    for app_id, spec in specs.items():
        summary = {category: 0 for category in SUMMARY_ORDER}
        elements = []
        for category, values in spec["noise"].items():
            summary[category] = int(values["noise_elements"])
            for index in range(int(values["noise_elements"])):
                elements.append(
                    {
                        "path": "synthetic://{}/{}/{}".format(app_id, category, index),
                        "category": category,
                        "reason": "synthetic {}".format(category),
                    }
                )
        payload = {
            "apk_path": None,
            "timestamp": utc_timestamp(),
            "elements": elements,
            "summary": summary,
        }
        analyses[app_id] = AppAnalysis(
            app_id=app_id,
            source_mode="synthetic",
            full_graphs=[],
            filtered_graphs=[],
            full_graph_tokens=list(spec["full"]),
            filtered_graph_tokens=list(spec["filtered"]),
            noise_source="synthetic_fixture",
            noise_payload=payload,
            noise_elements_by_category={category: int(values["noise_elements"]) for category, values in spec["noise"].items()},
            graphs_filtered_by_category={category: int(values["graphs_filtered"]) for category, values in spec["noise"].items()},
            warnings=[],
        )
    return analyses


def evaluate_synthetic_pairs(
    app_analyses: Dict[str, AppAnalysis],
    pair_specs: Sequence[Dict[str, str]],
) -> List[Dict[str, Any]]:
    results = []
    for pair_spec in pair_specs:
        analysis_a = app_analyses[pair_spec["app_a"]]
        analysis_b = app_analyses[pair_spec["app_b"]]
        score_without = score_synthetic_tokens(analysis_a.full_graph_tokens, analysis_b.full_graph_tokens)
        score_with = score_synthetic_tokens(analysis_a.filtered_graph_tokens, analysis_b.filtered_graph_tokens)
        results.append(
            build_pair_result(
                pair_id=pair_spec["pair"],
                app_a=analysis_a,
                app_b=analysis_b,
                score_with=score_with,
                score_without=score_without,
            )
        )
    return results


def score_synthetic_tokens(tokens_a: Sequence[str], tokens_b: Sequence[str]) -> float:
    if not tokens_a or not tokens_b:
        return 0.0
    set_a = set(tokens_a)
    set_b = set(tokens_b)
    denominator = max(len(set_a), len(set_b))
    if denominator == 0:
        return 0.0
    return float(len(set_a & set_b) / denominator)


def finalize_report(
    mode: str,
    apk_root: Optional[Path],
    output_path: Optional[Path],
    pair_results: List[Dict[str, Any]],
    app_analyses: Dict[str, AppAnalysis],
    warnings: Sequence[str],
) -> Dict[str, Any]:
    ranking_with = build_ranking(pair_results, "score_with")
    ranking_without = build_ranking(pair_results, "score_without")

    for pair_result in pair_results:
        pair_key = pair_result["pair"]
        pair_result["ranking_with"] = ranking_with[pair_key]
        pair_result["ranking_without"] = ranking_without[pair_key]
        pair_result["ranking_changed"] = ranking_with[pair_key] != ranking_without[pair_key]

    summary = build_summary(pair_results)
    conclusion = build_conclusion(summary)
    human_summary = build_human_summary(
        mode=mode,
        apk_root=apk_root,
        pair_results=pair_results,
        summary=summary,
        conclusion=conclusion,
        warnings=warnings,
    )

    report = {
        "generated_at_utc": utc_timestamp(),
        "mode": mode,
        "apk_dir": str(apk_root) if apk_root is not None else None,
        "pairs": pair_results,
        "summary": summary,
        "conclusion": conclusion,
        "warnings": unique_strings(list(warnings)),
        "apps": build_app_section(app_analyses),
        "human_summary": human_summary,
        "artifacts": {
            "json_report": str(output_path) if output_path is not None else None,
            "text_summary": str(summary_output_path(output_path)) if output_path is not None else None,
        },
    }
    if output_path is not None:
        write_report(report, output_path)
    return report


def build_ranking(pair_results: Sequence[Dict[str, Any]], score_key: str) -> Dict[str, int]:
    ordered = sorted(
        pair_results,
        key=lambda item: (-float(item[score_key]), item["pair"]),
    )
    return {item["pair"]: index + 1 for index, item in enumerate(ordered)}


def build_summary(pair_results: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    if not pair_results:
        return {
            "pair_count": 0,
            "mean_delta": 0.0,
            "max_delta": 0.0,
            "max_delta_pair": None,
            "min_delta": 0.0,
            "min_delta_pair": None,
            "max_abs_delta": 0.0,
            "max_abs_delta_pair": None,
            "pairs_where_delta_gt_0_05": [],
            "pairs_where_abs_delta_gt_0_05": [],
            "pairs_where_ranking_changed": [],
            "category_impact": [],
        }

    deltas = [float(item["delta"]) for item in pair_results]
    max_pair = max(pair_results, key=lambda item: float(item["delta"]))
    min_pair = min(pair_results, key=lambda item: float(item["delta"]))
    max_abs_pair = max(pair_results, key=lambda item: abs(float(item["delta"])))
    pairs_where_delta_gt = [item["pair"] for item in pair_results if float(item["delta"]) > 0.05]
    pairs_where_abs_delta_gt = [item["pair"] for item in pair_results if abs(float(item["delta"])) > 0.05]
    pairs_where_ranking_changed = [item["pair"] for item in pair_results if item.get("ranking_changed")]

    return {
        "pair_count": len(pair_results),
        "mean_delta": round(float(sum(deltas) / len(deltas)), 6),
        "max_delta": round(float(max_pair["delta"]), 6),
        "max_delta_pair": max_pair["pair"],
        "min_delta": round(float(min_pair["delta"]), 6),
        "min_delta_pair": min_pair["pair"],
        "max_abs_delta": round(abs(float(max_abs_pair["delta"])), 6),
        "max_abs_delta_pair": max_abs_pair["pair"],
        "pairs_where_delta_gt_0_05": pairs_where_delta_gt,
        "pairs_where_abs_delta_gt_0_05": pairs_where_abs_delta_gt,
        "pairs_where_ranking_changed": pairs_where_ranking_changed,
        "category_impact": build_category_impact(pair_results),
    }


def build_category_impact(pair_results: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    stats = {}
    pair_sets = defaultdict(set)
    for category in SUMMARY_ORDER:
        stats[category] = {
            "noise_elements": 0,
            "graphs_filtered": 0,
            "weighted_abs_delta": 0.0,
            "max_abs_delta_seen": 0.0,
        }

    for pair_result in pair_results:
        abs_delta = abs(float(pair_result["delta"]))
        total_graphs_filtered = max(1, int(pair_result.get("graphs_filtered", 0)))
        for category, values in pair_result["noise_by_category"].items():
            noise_elements = int(values.get("noise_elements", 0))
            graphs_filtered = int(values.get("graphs_filtered", 0))
            if noise_elements <= 0 and graphs_filtered <= 0:
                continue
            stats[category]["noise_elements"] += noise_elements
            stats[category]["graphs_filtered"] += graphs_filtered
            if graphs_filtered > 0:
                stats[category]["weighted_abs_delta"] += abs_delta * (graphs_filtered / total_graphs_filtered)
                stats[category]["max_abs_delta_seen"] = max(stats[category]["max_abs_delta_seen"], abs_delta)
            pair_sets[category].add(pair_result["pair"])

    result = []
    for category in SUMMARY_ORDER:
        if not pair_sets[category]:
            continue
        result.append(
            {
                "category": category,
                "pairs_touched": len(pair_sets[category]),
                "noise_elements": int(stats[category]["noise_elements"]),
                "graphs_filtered": int(stats[category]["graphs_filtered"]),
                "weighted_abs_delta": round(float(stats[category]["weighted_abs_delta"]), 6),
                "max_abs_delta_seen": round(float(stats[category]["max_abs_delta_seen"]), 6),
            }
        )
    result.sort(key=lambda item: (-item["weighted_abs_delta"], -item["graphs_filtered"], -item["noise_elements"], item["category"]))
    return result


def build_conclusion(summary: Dict[str, Any]) -> Dict[str, Any]:
    category_impact = summary.get("category_impact", [])
    if not category_impact:
        return {
            "top_categories": [],
            "inference_method": (
                "Categories are ordered by weighted_abs_delta, which distributes each pair |delta| "
                "proportionally to the number of filtered graphs in that category."
            ),
            "message": "No measurable noise categories were observed in the evaluated pairs.",
        }

    top_categories = [item["category"] for item in category_impact[:3]]
    impactful = [item for item in category_impact if float(item["weighted_abs_delta"]) > 0]
    if impactful:
        message = (
            "Largest measured score shifts are associated with categories {}.".format(", ".join(top_categories))
        )
    else:
        message = (
            "Noise categories were detected, but none produced measurable score changes in this code-only M_static comparison."
        )
    return {
        "top_categories": top_categories,
        "inference_method": (
            "Categories are ordered by weighted_abs_delta, which distributes each pair |delta| "
            "proportionally to the number of filtered graphs in that category."
        ),
        "message": message,
    }


def build_app_section(app_analyses: Dict[str, AppAnalysis]) -> List[Dict[str, Any]]:
    result = []
    for app_id in sorted(app_analyses):
        analysis = app_analyses[app_id]
        full_count = len(analysis.full_graphs) if analysis.source_mode == "real" else len(analysis.full_graph_tokens)
        filtered_count = len(analysis.filtered_graphs) if analysis.source_mode == "real" else len(analysis.filtered_graph_tokens)
        result.append(
            {
                "app_id": analysis.app_id,
                "noise_source": analysis.noise_source,
                "full_graph_count": full_count,
                "filtered_graph_count": filtered_count,
                "noise_elements_by_category": analysis.noise_elements_by_category,
                "graphs_filtered_by_category": analysis.graphs_filtered_by_category,
                "warnings": analysis.warnings,
            }
        )
    return result


def build_human_summary(
    mode: str,
    apk_root: Optional[Path],
    pair_results: Sequence[Dict[str, Any]],
    summary: Dict[str, Any],
    conclusion: Dict[str, Any],
    warnings: Sequence[str],
) -> str:
    lines = []
    lines.append("Noise Ablation Study")
    lines.append("Generated at UTC: {}".format(utc_timestamp()))
    lines.append("Mode: {}".format(mode))
    if apk_root is not None:
        lines.append("APK root: {}".format(apk_root))
    lines.append("")
    lines.append("Pair".ljust(36) + "with".rjust(10) + "without".rjust(12) + "delta".rjust(10) + "noise".rjust(10) + "graphs".rjust(10))
    lines.append("-" * 88)
    for pair_result in pair_results:
        lines.append(
            "{}{}{}{}{}{}".format(
                trim_text(pair_result["pair"], 36).ljust(36),
                "{:.4f}".format(float(pair_result["score_with"])).rjust(10),
                "{:.4f}".format(float(pair_result["score_without"])).rjust(12),
                "{:+.4f}".format(float(pair_result["delta"])).rjust(10),
                str(int(pair_result["noise_elements_filtered"])).rjust(10),
                str(int(pair_result["graphs_filtered"])).rjust(10),
            )
        )

    lines.append("")
    lines.append("Summary")
    lines.append("- mean_delta: {:+.6f}".format(float(summary["mean_delta"])))
    lines.append("- max_delta: {:+.6f} ({})".format(float(summary["max_delta"]), summary["max_delta_pair"]))
    lines.append("- max_abs_delta: {:.6f} ({})".format(float(summary["max_abs_delta"]), summary["max_abs_delta_pair"]))
    lines.append("- pairs_where_delta_gt_0_05: {}".format(", ".join(summary["pairs_where_delta_gt_0_05"]) or "none"))
    lines.append(
        "- pairs_where_ranking_changed: {}".format(", ".join(summary["pairs_where_ranking_changed"]) or "none")
    )

    lines.append("")
    lines.append("Top Noise Categories")
    category_impact = summary.get("category_impact", [])
    if category_impact:
        for category in category_impact[:3]:
            lines.append(
                "- {}: weighted_abs_delta={}, graphs_filtered={}, noise_elements={}".format(
                    category["category"],
                    "{:.6f}".format(float(category["weighted_abs_delta"])),
                    category["graphs_filtered"],
                    category["noise_elements"],
                )
            )
    else:
        lines.append("- none")

    lines.append("")
    lines.append("Conclusion")
    lines.append("- {}".format(conclusion["message"]))

    if warnings:
        lines.append("")
        lines.append("Warnings")
        for warning in unique_strings(list(warnings)):
            lines.append("- {}".format(warning))

    return os.linesep.join(lines)


def trim_text(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    if limit <= 1:
        return value[:limit]
    return value[: limit - 1] + "…"


def summary_output_path(output_path: Path) -> Path:
    suffix = output_path.suffix or ".json"
    return output_path.with_suffix(suffix + ".summary.txt")


def write_report(report: Dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + os.linesep, encoding="utf-8")
    summary_path = summary_output_path(output_path)
    summary_path.write_text(report["human_summary"] + os.linesep, encoding="utf-8")


def unique_strings(values: Iterable[str]) -> List[str]:
    ordered = []
    seen = set()
    for value in values:
        if not value:
            continue
        if value in seen:
            continue
        seen.add(value)
        ordered.append(value)
    return ordered


@contextmanager
def working_directory(path: Path):
    previous = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


if __name__ == "__main__":
    raise SystemExit(main())
