#!/usr/bin/env python3
"""SOTA-010: A/B comparison library_view v1 vs v2 on F-Droid APKs.

Reads APKs directly (no apktool needed) via zipfile to extract smali/class paths.
Compares library_like classification counts between v1 (prefix-match) and v2 (Jaccard).

Usage:
    python3 script/run_sota010_ab_library_comparison.py
"""

from __future__ import annotations

import json
import sys
import time
import zipfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

APK_DIR = Path(
    "/Users/valeryvpetrov/Documents/obsidian/valeryvpetrov/phd/"
    "experiments/datasets/fdroid-corpus-v1-apks"
)
OUT_DIR = Path(
    "/Users/valeryvpetrov/Documents/obsidian/valeryvpetrov/phd/"
    "experiments/artifacts/E-SOTA-010"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Helpers — file list from APK (zip)
# ---------------------------------------------------------------------------

def list_apk_entries(apk_path: Path) -> List[str]:
    """Return all file paths inside APK (APK = ZIP)."""
    try:
        with zipfile.ZipFile(apk_path, "r") as zf:
            return [info.filename for info in zf.infolist() if not info.is_dir()]
    except Exception as exc:
        raise RuntimeError("zipfile failed: {}".format(exc)) from exc


# ---------------------------------------------------------------------------
# v1: prefix-match (pure path-based, no androguard)
# ---------------------------------------------------------------------------

def classify_v1(rel_paths: List[str]) -> int:
    """Count files classified as library_like using v1 prefix logic."""
    from noise_normalizer import detect_library_like, detect_autogenerated_like
    from noise_normalizer import detect_packaging_noise

    count = 0
    for rel_path in rel_paths:
        # Replicate noise_normalizer.classify_file order (skip unstable — needs disk)
        if detect_packaging_noise(Path(rel_path), rel_path) is not None:
            continue
        if detect_autogenerated_like(rel_path) is not None:
            continue
        result = detect_library_like(rel_path)
        if result is not None:
            count += 1
    return count


# ---------------------------------------------------------------------------
# v2: package-set Jaccard
# ---------------------------------------------------------------------------

def classify_v2(
    apk_path: Path,
    rel_paths: List[str],
    cache_dir: Optional[Path] = None,
) -> Tuple[int, Optional[Dict], Optional[str]]:
    """Count files classified as library_like using v2 Jaccard logic.

    Returns (count, tpl_detections_dict, error_str_or_None).
    """
    from noise_normalizer import detect_autogenerated_like, detect_packaging_noise
    from library_view_v2 import (
        extract_apk_packages,
        detect_tpl_in_packages,
        detect_library_like_v2,
    )

    # Extract APK packages via androguard
    try:
        apk_packages = extract_apk_packages(
            str(apk_path),
            cache_dir=str(cache_dir) if cache_dir else None,
        )
    except Exception as exc:
        return 0, None, "extract_apk_packages failed: {}".format(exc)

    tpl_detections = detect_tpl_in_packages(apk_packages)

    count = 0
    for rel_path in rel_paths:
        if detect_packaging_noise(Path(rel_path), rel_path) is not None:
            continue
        if detect_autogenerated_like(rel_path) is not None:
            continue
        result = detect_library_like_v2(
            rel_path,
            apk_packages=apk_packages,
            tpl_detections=tpl_detections,
        )
        if result is not None:
            count += 1
    return count, tpl_detections, None


# ---------------------------------------------------------------------------
# Per-APK run
# ---------------------------------------------------------------------------

def run_apk(apk_path: Path, cache_dir: Path) -> Dict:
    """Run A/B comparison for a single APK. Returns result dict."""
    result: Dict = {
        "apk": apk_path.name,
        "v1_library_count": 0,
        "v2_library_count": 0,
        "v2_new_detections": 0,
        "v2_tpls_detected": [],
        "latency_v2_sec": 0.0,
        "error": None,
    }

    # List entries
    try:
        rel_paths = list_apk_entries(apk_path)
    except Exception as exc:
        result["error"] = str(exc)
        return result

    # v1
    try:
        v1_count = classify_v1(rel_paths)
        result["v1_library_count"] = v1_count
    except Exception as exc:
        result["error"] = "v1 failed: {}".format(exc)
        return result

    # v2
    t0 = time.perf_counter()
    try:
        v2_count, tpl_dets, v2_err = classify_v2(apk_path, rel_paths, cache_dir=cache_dir)
    except Exception as exc:
        result["error"] = "v2 failed: {}".format(exc)
        return result
    latency = time.perf_counter() - t0

    result["latency_v2_sec"] = round(latency, 3)

    if v2_err:
        result["error"] = v2_err
        # Still record v1 result
        return result

    result["v2_library_count"] = v2_count
    result["v2_new_detections"] = max(0, v2_count - v1_count)

    # Collect detected TPL ids
    if tpl_dets:
        result["v2_tpls_detected"] = [
            tpl_id for tpl_id, info in tpl_dets.items() if info.get("detected")
        ]

    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    apk_files = sorted(APK_DIR.glob("*.apk"))
    print("Found {} APKs in {}".format(len(apk_files), APK_DIR))

    cache_dir = OUT_DIR / "androguard_cache"
    cache_dir.mkdir(parents=True, exist_ok=True)

    results: List[Dict] = []
    errors: List[str] = []

    for idx, apk_path in enumerate(apk_files, 1):
        print("[{}/{}] {}".format(idx, len(apk_files), apk_path.name), end=" ... ", flush=True)
        res = run_apk(apk_path, cache_dir)
        results.append(res)
        if res["error"]:
            errors.append("{}: {}".format(apk_path.name, res["error"]))
            print("ERROR: {}".format(res["error"]))
        else:
            print("v1={} v2={} new={} tpls={} lat={:.2f}s".format(
                res["v1_library_count"],
                res["v2_library_count"],
                res["v2_new_detections"],
                len(res["v2_tpls_detected"]),
                res["latency_v2_sec"],
            ))

    # ---------------------------------------------------------------------------
    # Aggregates
    # ---------------------------------------------------------------------------
    ok_results = [r for r in results if not r["error"]]
    n = len(ok_results)
    if n == 0:
        print("\nAll APKs failed — no aggregates.")
        return

    avg_v1 = sum(r["v1_library_count"] for r in ok_results) / n
    avg_v2 = sum(r["v2_library_count"] for r in ok_results) / n
    avg_lat = sum(r["latency_v2_sec"] for r in ok_results) / n
    apks_v2_gt_v1 = sum(1 for r in ok_results if r["v2_library_count"] > r["v1_library_count"])
    apks_any_tpl = sum(1 for r in ok_results if r["v2_tpls_detected"])
    total_new = sum(r["v2_new_detections"] for r in ok_results)
    pct_tpl = 100.0 * apks_any_tpl / n if n else 0.0

    aggregate = {
        "total_apks": len(apk_files),
        "ok_apks": n,
        "error_apks": len(errors),
        "avg_v1_library_per_apk": round(avg_v1, 1),
        "avg_v2_library_per_apk": round(avg_v2, 1),
        "avg_latency_v2_sec": round(avg_lat, 3),
        "apks_v2_gt_v1": apks_v2_gt_v1,
        "apks_with_tpl_detected_v2": apks_any_tpl,
        "pct_apks_with_tpl_v2": round(pct_tpl, 1),
        "total_new_detections_v2_over_v1": total_new,
        "errors": errors,
    }

    # Save raw results
    raw_out = OUT_DIR / "sota-010-ab-raw-results.json"
    raw_out.write_text(
        json.dumps({"aggregate": aggregate, "per_apk": results}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print("\nRaw results saved to: {}".format(raw_out))

    # Print summary
    print("\n=== AGGREGATE SUMMARY ===")
    print("APKs processed: {}/{}  (errors: {})".format(n, len(apk_files), len(errors)))
    print("Avg library files/APK  v1={:.1f}  v2={:.1f}".format(avg_v1, avg_v2))
    print("APKs where v2 > v1: {}".format(apks_v2_gt_v1))
    print("APKs with ≥1 TPL detected (v2): {} / {} ({:.1f}%)".format(
        apks_any_tpl, n, pct_tpl))
    print("Total new v2 detections (over v1): {}".format(total_new))
    print("Avg v2 latency: {:.3f}s".format(avg_lat))
    if errors:
        print("\nErrors ({}):\n  {}".format(len(errors), "\n  ".join(errors)))


if __name__ == "__main__":
    main()
