#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


FORMAT_VERSION = "screening-explanation-v1"
MAX_DOMINANT_SIGNALS = 3
MAX_EVIDENCE_ITEMS = 5
MAX_NOISE_ELEMENTS = 10
ALLOWED_MATCHED_LAYERS = ("code", "component", "resource", "metadata", "library")
ALLOWED_NOISE_CLASSES = (
    "library_like",
    "autogenerated_like",
    "packaging_noise",
    "unstable_extraction_risk",
)

LAYER_ALIASES = {
    "apk": "metadata",
    "apk_entry": "metadata",
    "apk_structure": "metadata",
    "code": "code",
    "component": "component",
    "components": "component",
    "graph": "code",
    "library": "library",
    "library_profile": "library",
    "manifest": "metadata",
    "metadata": "metadata",
    "package": "metadata",
    "resource": "resource",
    "resources": "resource",
}
NOISE_CLASS_ALIASES = {
    "autogenerated": "autogenerated_like",
    "autogenerated_like": "autogenerated_like",
    "generated": "autogenerated_like",
    "library": "library_like",
    "library_like": "library_like",
    "packaging": "packaging_noise",
    "packaging_noise": "packaging_noise",
    "risk": "unstable_extraction_risk",
    "unstable": "unstable_extraction_risk",
    "unstable_extraction_risk": "unstable_extraction_risk",
}
DEFAULT_NOISE_LAYER = {
    "library_like": "library",
    "autogenerated_like": "component",
    "packaging_noise": "metadata",
    "unstable_extraction_risk": "metadata",
}
DEFAULT_NOISE_ACTION = {
    "library_like": "downweighted",
    "autogenerated_like": "removed",
    "packaging_noise": "removed",
    "unstable_extraction_risk": "kept_as_warning",
}
DEFAULT_NOISE_REASON = {
    "library_like": "общая сторонняя библиотека не должна доминировать в предварительном отборе",
    "autogenerated_like": "autogenerated framework-артефакты не несут прикладной семантики сходства",
    "packaging_noise": "упаковочные артефакты завышают структурную близость APK",
    "unstable_extraction_risk": "нестабильное извлечение требует осторожной интерпретации",
}
SIGNAL_LABELS = {
    "package_name_overlap": "совпадение package name",
    "code_shape_overlap": "совпадения по формам графов кода",
    "component_overlap": "совпадения по прикладным компонентам",
    "resource_profile_overlap": "совпадения по ресурсному профилю",
    "apk_structure_overlap": "совпадения по структуре APK",
    "library_profile_overlap": "совпадения по библиотечному профилю",
    "code_volume_ratio": "близость по объему CFG-графов",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate screening_explanation objects for shortlist candidates."
    )
    parser.add_argument("--candidates", required=True, help="Path to candidate_list JSON from screening_runner.")
    parser.add_argument("--noise", required=True, help="Path to noise_report JSON from noise_normalizer.")
    parser.add_argument("--output", required=True, help="Path to output JSON.")
    return parser.parse_args()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def get_first(mapping: dict[str, Any], keys: tuple[str, ...], default: Any = None) -> Any:
    for key in keys:
        if key in mapping and mapping[key] not in (None, "", [], {}):
            return mapping[key]
    return default


def as_float(value: Any, default: float = 0.0) -> float:
    if value in (None, "", False):
        return default
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(str(value).strip())
    except ValueError:
        return default


def as_int(value: Any, default: int = 0) -> int:
    if value in (None, "", False):
        return default
    if isinstance(value, bool):
        return 1 if value else 0
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    try:
        return int(float(str(value).strip()))
    except ValueError:
        return default


def as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    if value is None:
        return False
    normalized = str(value).strip().lower()
    return normalized in {"1", "true", "yes", "y", "on", "matched"}


def split_strings(value: Any) -> list[str]:
    if value in (None, "", [], {}):
        return []
    if isinstance(value, list):
        items = value
    elif isinstance(value, tuple):
        items = list(value)
    elif isinstance(value, set):
        items = sorted(value)
    elif isinstance(value, str):
        items = value.replace("\n", "|").replace(",", "|").split("|")
    else:
        items = [value]

    result: list[str] = []
    for item in items:
        text = str(item).strip()
        if text:
            result.append(text)
    return result


def unique_strings(values: list[str], limit: int | None = None) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
        if limit is not None and len(result) >= limit:
            break
    return result


def canonical_layer(raw_layer: Any) -> str:
    if raw_layer is None:
        return ""
    normalized = str(raw_layer).strip().lower()
    if normalized in ALLOWED_MATCHED_LAYERS:
        return normalized
    return LAYER_ALIASES.get(normalized, "")


def canonical_noise_class(raw_value: Any) -> str:
    if raw_value is None:
        return ""
    normalized = str(raw_value).strip().lower()
    if normalized in ALLOWED_NOISE_CLASSES:
        return normalized
    return NOISE_CLASS_ALIASES.get(normalized, "")


def normalize_candidate_rows(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        raise ValueError("candidate_list JSON must be a list or an object wrapper.")

    for key in ("candidate_list", "candidates", "rows", "results", "items", "data"):
        value = payload.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, dict)]
        if isinstance(value, dict):
            extracted = []
            for nested_key, nested_value in value.items():
                if isinstance(nested_value, dict):
                    row = dict(nested_value)
                    row.setdefault("row_id", nested_key)
                    extracted.append(row)
            if extracted:
                return extracted

    if any(key in payload for key in ("app_a", "app_b", "query_app_id", "candidate_app_id")):
        return [payload]

    extracted = []
    for nested_key, nested_value in payload.items():
        if isinstance(nested_value, dict):
            row = dict(nested_value)
            row.setdefault("row_id", nested_key)
            extracted.append(row)
    if extracted:
        return extracted
    raise ValueError("Unable to find candidate rows in candidate_list JSON.")


def normalize_noise_rows(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        return []

    for key in ("noise_report", "reports", "rows", "items", "data", "noise_profiles"):
        value = payload.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, dict)]
        if isinstance(value, dict):
            rows = []
            for nested_key, nested_value in value.items():
                if isinstance(nested_value, dict):
                    row = dict(nested_value)
                    if "app_id" not in row and "pair_id" not in row and "pair_key" not in row:
                        if "__" in nested_key:
                            row["pair_key"] = nested_key
                        else:
                            row["app_id"] = nested_key
                    rows.append(row)
            if rows:
                return rows

    rows = []
    for nested_key, nested_value in payload.items():
        if isinstance(nested_value, dict):
            row = dict(nested_value)
            if "app_id" not in row and "pair_id" not in row and "pair_key" not in row:
                if "__" in nested_key:
                    row["pair_key"] = nested_key
                else:
                    row["app_id"] = nested_key
            rows.append(row)
    return rows


def pair_lookup_keys(app_a: str, app_b: str) -> list[str]:
    ordered = [
        f"{app_a}::{app_b}",
        f"{app_b}::{app_a}",
        f"{app_a}__{app_b}",
        f"{app_b}__{app_a}",
        f"{app_a}|{app_b}",
        f"{app_b}|{app_a}",
        "__".join(sorted([app_a, app_b])),
    ]
    return unique_strings([key for key in ordered if app_a and app_b])


def build_noise_index(rows: list[dict[str, Any]]) -> tuple[dict[str, list[dict[str, Any]]], dict[str, list[dict[str, Any]]]]:
    pair_index: dict[str, list[dict[str, Any]]] = {}
    app_index: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        pair_id = get_first(row, ("pair_id", "pair_key"), "")
        query_app_id = get_first(row, ("query_app_id", "app_a"), "")
        candidate_app_id = get_first(row, ("candidate_app_id", "app_b"), "")
        app_id = get_first(row, ("app_id",), "")

        keys = []
        if pair_id:
            keys.append(str(pair_id))
        keys.extend(pair_lookup_keys(str(query_app_id), str(candidate_app_id)))
        for key in unique_strings([item for item in keys if item]):
            pair_index.setdefault(key, []).append(row)

        for normalized_app_id in unique_strings(
            [str(item) for item in (app_id, query_app_id, candidate_app_id) if item]
        ):
            app_index.setdefault(normalized_app_id, []).append(row)
    return pair_index, app_index


def default_noise_entry(noise_class: str, elements: list[str] | None = None, reason: str = "") -> dict[str, Any]:
    normalized_class = canonical_noise_class(noise_class)
    if not normalized_class:
        return {}
    return {
        "noise_class": normalized_class,
        "source_layer": DEFAULT_NOISE_LAYER[normalized_class],
        "filter_action": DEFAULT_NOISE_ACTION[normalized_class],
        "elements": unique_strings(elements or [], limit=MAX_NOISE_ELEMENTS),
        "reason": reason or DEFAULT_NOISE_REASON[normalized_class],
    }


def normalize_noise_item(raw_item: dict[str, Any], default_class: str = "") -> dict[str, Any]:
    noise_class = canonical_noise_class(get_first(raw_item, ("noise_class", "class", "type"), default_class))
    if not noise_class:
        return {}

    source_layer = canonical_layer(get_first(raw_item, ("source_layer", "layer"), DEFAULT_NOISE_LAYER[noise_class]))
    if not source_layer:
        source_layer = DEFAULT_NOISE_LAYER[noise_class]

    filter_action = str(
        get_first(raw_item, ("filter_action", "action"), DEFAULT_NOISE_ACTION[noise_class])
    ).strip()
    if not filter_action:
        filter_action = DEFAULT_NOISE_ACTION[noise_class]

    elements = unique_strings(
        split_strings(
            get_first(
                raw_item,
                ("elements", "items", "tokens", "warnings", "matches"),
                [],
            )
        ),
        limit=MAX_NOISE_ELEMENTS,
    )
    count = as_int(get_first(raw_item, ("count", "value"), 0))
    if not elements and count > 0:
        elements = []

    reason = str(get_first(raw_item, ("reason", "summary"), DEFAULT_NOISE_REASON[noise_class])).strip()
    if not reason:
        reason = DEFAULT_NOISE_REASON[noise_class]

    return {
        "noise_class": noise_class,
        "source_layer": source_layer,
        "filter_action": filter_action,
        "elements": elements,
        "reason": reason,
    }


def extract_noise_items_from_container(container: Any) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    if isinstance(container, list):
        for item in container:
            if isinstance(item, dict):
                normalized = normalize_noise_item(item)
                if normalized:
                    items.append(normalized)
        return items

    if isinstance(container, dict):
        if any(key in container for key in ("noise_class", "class", "type", "elements", "items")):
            normalized = normalize_noise_item(container)
            return [normalized] if normalized else []

        for key, value in container.items():
            noise_class = canonical_noise_class(key)
            if not noise_class:
                continue
            if isinstance(value, dict):
                normalized = normalize_noise_item(value, default_class=noise_class)
                if normalized:
                    items.append(normalized)
            else:
                default_entry = default_noise_entry(noise_class, split_strings(value))
                if default_entry:
                    items.append(default_entry)
    return items


def extract_noise_items(row: dict[str, Any]) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for key in (
        "filtered_as_noise",
        "filtered_noise",
        "noise_items",
        "noise_elements",
        "noise_profile",
        "noise_report",
    ):
        items.extend(extract_noise_items_from_container(row.get(key)))

    for noise_class in ALLOWED_NOISE_CLASSES:
        elements = split_strings(
            get_first(
                row,
                (
                    f"{noise_class}_elements",
                    f"{noise_class}_items",
                    f"{noise_class}_tokens",
                    f"{noise_class}_warnings",
                ),
                [],
            )
        )
        count = as_int(get_first(row, (f"{noise_class}_count",), 0))
        if elements or count > 0:
            item = default_noise_entry(noise_class, elements=elements)
            if item:
                explicit_action = get_first(row, (f"{noise_class}_filter_action",), "")
                explicit_reason = get_first(row, (f"{noise_class}_reason",), "")
                if explicit_action:
                    item["filter_action"] = str(explicit_action).strip()
                if explicit_reason:
                    item["reason"] = str(explicit_reason).strip()
                items.append(item)

    warnings = split_strings(
        get_first(row, ("normalization_warnings", "screening_warnings", "warnings"), [])
    )
    if warnings:
        items.append(
            {
                "noise_class": "unstable_extraction_risk",
                "source_layer": "metadata",
                "filter_action": "kept_as_warning",
                "elements": unique_strings(warnings, limit=MAX_NOISE_ELEMENTS),
                "reason": DEFAULT_NOISE_REASON["unstable_extraction_risk"],
            }
        )
    return merge_noise_items(items)


def merge_noise_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for item in items:
        if not item:
            continue
        key = (
            item["noise_class"],
            item["source_layer"],
            item["filter_action"],
            item["reason"],
        )
        if key not in merged:
            merged[key] = {
                "noise_class": item["noise_class"],
                "source_layer": item["source_layer"],
                "filter_action": item["filter_action"],
                "elements": [],
                "reason": item["reason"],
            }
        merged[key]["elements"].extend(split_strings(item.get("elements", [])))

    normalized_items = []
    for key in sorted(merged):
        item = merged[key]
        item["elements"] = unique_strings(item["elements"], limit=MAX_NOISE_ELEMENTS)
        normalized_items.append(item)
    return normalized_items


def collect_filtered_noise(
    app_a: str,
    app_b: str,
    pair_index: dict[str, list[dict[str, Any]]],
    app_index: dict[str, list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    collected_rows: list[dict[str, Any]] = []
    for key in pair_lookup_keys(app_a, app_b):
        collected_rows.extend(pair_index.get(key, []))
    for app_id in unique_strings([app_a, app_b]):
        collected_rows.extend(app_index.get(app_id, []))

    items: list[dict[str, Any]] = []
    for row in collected_rows:
        items.extend(extract_noise_items(row))
    return merge_noise_items(items)


def normalize_retrieval_features(row: dict[str, Any]) -> set[str]:
    features = set(
        item.lower()
        for item in split_strings(
            get_first(
                row,
                ("retrieval_features_used", "retrieval_features", "features_used", "features"),
                [],
            )
        )
    )
    strategy = get_first(row, ("retrieval_strategy", "strategy"), "")
    if strategy:
        features.add(str(strategy).strip().lower())
    return features


def signal_strength_from_value(score: float | None, value: Any) -> float:
    if score is not None and score > 0:
        return min(score, 1.0)
    numeric_value = as_float(value, 0.0)
    if numeric_value <= 0:
        return 0.0
    if 0.0 <= numeric_value <= 1.0:
        return numeric_value
    return 1.0 - (1.0 / (numeric_value + 1.0))


def format_score_value_text(label: str, score: float) -> str:
    return f"{label} (score {score:.4f})"


def build_value_text(signal_id: str, value: Any, score: float | None = None) -> str:
    numeric_value = as_float(value, 0.0)
    if signal_id == "package_name_overlap":
        if numeric_value >= 1:
            return "совпадающий package name"
        if score is not None and score > 0:
            return format_score_value_text("сходство package name", score)
    if signal_id == "code_shape_overlap":
        if numeric_value > 1:
            return f"{as_int(value)} общие формы графов кода"
        if numeric_value == 1:
            return "1 общая форма графа кода"
        if score is not None and score > 0:
            return format_score_value_text("сходство графов кода", score)
    if signal_id == "component_overlap":
        if numeric_value > 1:
            return f"{as_int(value)} общих прикладных компонентов"
        if numeric_value == 1:
            return "1 общий прикладной компонент"
        if score is not None and score > 0:
            return format_score_value_text("сходство компонентов", score)
    if signal_id == "resource_profile_overlap":
        if numeric_value > 1:
            return f"{as_int(value)} совпадающих признаков ресурсов"
        if numeric_value == 1:
            return "1 совпадающий признак ресурсов"
        if score is not None and score > 0:
            return format_score_value_text("сходство ресурсного профиля", score)
    if signal_id == "apk_structure_overlap":
        if numeric_value > 1:
            return f"{as_int(value)} совпадающих маркеров структуры APK"
        if numeric_value == 1:
            return "1 совпадающий маркер структуры APK"
        if score is not None and score > 0:
            return format_score_value_text("сходство структуры APK", score)
    if signal_id == "library_profile_overlap":
        if numeric_value > 1:
            return f"{as_int(value)} совпадений библиотечного профиля"
        if numeric_value == 1:
            return "1 совпадение библиотечного профиля"
        if score is not None and score > 0:
            return format_score_value_text("сходство библиотечного профиля", score)
    if signal_id == "code_volume_ratio":
        if score is not None and score > 0:
            return f"близкий объем CFG-графов (отношение {score:.4f})"
        if numeric_value > 0:
            return f"близкий объем CFG-графов (отношение {numeric_value:.4f})"
    label = SIGNAL_LABELS.get(signal_id, signal_id)
    if numeric_value > 0:
        return f"{label}: {numeric_value:.4f}" if numeric_value <= 1 else f"{label}: {as_int(value)}"
    if score is not None and score > 0:
        return format_score_value_text(label, score)
    return label


def build_signal(
    signal_id: str,
    layer: str,
    value: Any,
    evidence: list[str],
    retrieval_features: set[str],
    retrieval_aliases: tuple[str, ...],
    score: float | None = None,
) -> dict[str, Any] | None:
    normalized_layer = canonical_layer(layer)
    if not normalized_layer:
        return None

    normalized_score = None
    if score is not None:
        normalized_score = as_float(score, 0.0)
    normalized_value = value
    if isinstance(value, (int, float)) and as_float(value, 0.0) <= 0 and (normalized_score or 0) <= 0:
        return None
    if isinstance(value, str) and not str(value).strip() and (normalized_score or 0) <= 0:
        return None

    used_in_retrieval = any(alias.lower() in retrieval_features for alias in retrieval_aliases)
    strength = signal_strength_from_value(normalized_score, normalized_value)
    if strength <= 0:
        return None
    if used_in_retrieval:
        strength = min(strength + 0.2, 1.2)

    return {
        "signal_id": signal_id,
        "layer": normalized_layer,
        "used_in_retrieval": used_in_retrieval,
        "contribution_role": "direct" if used_in_retrieval else "supporting",
        "value": normalized_value,
        "value_text": build_value_text(signal_id, normalized_value, normalized_score),
        "evidence": unique_strings(evidence, limit=MAX_EVIDENCE_ITEMS),
        "_sort_strength": strength,
    }


def extract_explicit_signals(
    row: dict[str, Any],
    retrieval_features: set[str],
) -> list[dict[str, Any]]:
    explicit = get_first(row, ("signals", "retrieval_signals", "dominant_signals"), [])
    if not isinstance(explicit, list):
        return []

    signals: list[dict[str, Any]] = []
    for item in explicit:
        if not isinstance(item, dict):
            continue
        signal_id = str(get_first(item, ("signal_id", "id"), "")).strip()
        layer = canonical_layer(get_first(item, ("layer",), ""))
        if not signal_id or not layer:
            continue
        used_in_retrieval = as_bool(get_first(item, ("used_in_retrieval",), False))
        if not used_in_retrieval:
            used_in_retrieval = signal_id.lower() in retrieval_features
        value = get_first(item, ("value", "count", "score"), 0)
        score = None
        if "score" in item:
            score = as_float(item.get("score"), 0.0)
        signal = build_signal(
            signal_id=signal_id,
            layer=layer,
            value=value,
            evidence=split_strings(get_first(item, ("evidence", "examples"), [])),
            retrieval_features=retrieval_features | ({signal_id.lower()} if used_in_retrieval else set()),
            retrieval_aliases=(signal_id,),
            score=score,
        )
        if signal:
            if item.get("value_text"):
                signal["value_text"] = str(item["value_text"]).strip()
            signals.append(signal)
    return signals


def build_metric_signals(row: dict[str, Any], retrieval_features: set[str]) -> list[dict[str, Any]]:
    signals: list[dict[str, Any]] = []

    query_package = str(get_first(row, ("query_package_name", "app_a_package_name"), "")).strip()
    candidate_package = str(get_first(row, ("candidate_package_name", "app_b_package_name"), "")).strip()
    package_match = bool(query_package and candidate_package and query_package == candidate_package)
    package_value = get_first(
        row,
        ("package_name_overlap_count", "shared_package_count", "package_name_jaccard", "package_name_match"),
        1 if package_match else 0,
    )
    package_evidence = split_strings(
        get_first(row, ("shared_package_names", "top_package_name_overlap"), [])
    )
    if package_match:
        package_evidence = [query_package] + package_evidence
    signal = build_signal(
        signal_id="package_name_overlap",
        layer="metadata",
        value=package_value,
        evidence=package_evidence,
        retrieval_features=retrieval_features,
        retrieval_aliases=("package_name_overlap", "package_name_jaccard", "package_name_reuse"),
        score=as_float(get_first(row, ("package_name_jaccard", "package_name_similarity"), 0.0), 0.0),
    )
    if signal:
        signals.append(signal)

    signal = build_signal(
        signal_id="code_shape_overlap",
        layer="code",
        value=get_first(
            row,
            ("code_shape_overlap_count", "shared_graph_count", "code_graph_overlap_count"),
            0,
        ),
        evidence=split_strings(
            get_first(row, ("top_code_shape_overlap", "top_graph_overlap", "shared_graphs"), [])
        ),
        retrieval_features=retrieval_features,
        retrieval_aliases=("graph_jaccard_v1", "shared_graph_count_v1", "code_shape_overlap"),
        score=as_float(get_first(row, ("code_shape_jaccard", "graph_jaccard"), 0.0), 0.0),
    )
    if signal:
        signals.append(signal)

    signal = build_signal(
        signal_id="component_overlap",
        layer="component",
        value=get_first(
            row,
            ("component_overlap_count", "shared_component_count", "shared_components_count"),
            0,
        ),
        evidence=split_strings(get_first(row, ("top_component_overlap", "shared_components"), [])),
        retrieval_features=retrieval_features,
        retrieval_aliases=("component_jaccard_v1", "component_overlap", "shared_components"),
        score=as_float(get_first(row, ("component_jaccard", "component_similarity"), 0.0), 0.0),
    )
    if signal:
        signals.append(signal)

    signal = build_signal(
        signal_id="resource_profile_overlap",
        layer="resource",
        value=get_first(
            row,
            ("resource_overlap_count", "apk_resource_overlap_count", "shared_resources_count"),
            0,
        ),
        evidence=split_strings(
            get_first(row, ("top_resource_overlap", "top_apk_resource_overlap", "shared_resources"), [])
        ),
        retrieval_features=retrieval_features,
        retrieval_aliases=("resource_jaccard_v1", "resource_overlap", "resource_similarity"),
        score=as_float(
            get_first(row, ("resource_jaccard", "apk_resource_jaccard", "resource_similarity"), 0.0),
            0.0,
        ),
    )
    if signal:
        signals.append(signal)

    signal = build_signal(
        signal_id="apk_structure_overlap",
        layer="metadata",
        value=get_first(
            row,
            ("apk_entry_overlap_count", "metadata_overlap_count", "manifest_overlap_count", "apk_structure_overlap_count"),
            0,
        ),
        evidence=split_strings(
            get_first(
                row,
                ("top_apk_entry_overlap", "top_metadata_overlap", "top_manifest_overlap", "shared_metadata"),
                [],
            )
        ),
        retrieval_features=retrieval_features,
        retrieval_aliases=("apk_structure_jaccard_v1", "apk_entry_jaccard", "apk_structure_overlap"),
        score=as_float(
            get_first(
                row,
                ("apk_entry_jaccard", "metadata_jaccard", "manifest_profile_jaccard", "apk_structure_jaccard"),
                0.0,
            ),
            0.0,
        ),
    )
    if signal:
        signals.append(signal)

    signal = build_signal(
        signal_id="library_profile_overlap",
        layer="library",
        value=get_first(
            row,
            ("library_profile_overlap_count", "shared_library_count", "shared_libraries_count"),
            0,
        ),
        evidence=split_strings(
            get_first(row, ("top_library_profile_overlap", "shared_libraries"), [])
        ),
        retrieval_features=retrieval_features,
        retrieval_aliases=("library_profile_jaccard_v1", "library_profile_overlap", "library_similarity"),
        score=as_float(
            get_first(row, ("library_profile_jaccard", "library_similarity"), 0.0),
            0.0,
        ),
    )
    if signal:
        signals.append(signal)

    graph_ratio = get_first(row, ("cfg_count_ratio", "code_volume_ratio"), None)
    if graph_ratio is None and (
        str(get_first(row, ("retrieval_strategy",), "")).strip().lower() == "cfg_count_ratio_v1"
    ):
        query_graph_count = as_float(get_first(row, ("query_graph_count",), 0.0), 0.0)
        candidate_graph_count = as_float(get_first(row, ("candidate_graph_count",), 0.0), 0.0)
        maximum = max(query_graph_count, candidate_graph_count)
        graph_ratio = (min(query_graph_count, candidate_graph_count) / maximum) if maximum else 0.0

    evidence = []
    if get_first(row, ("query_graph_count",), None) is not None:
        evidence.append(f"query_graph_count={as_int(row['query_graph_count'])}")
    if get_first(row, ("candidate_graph_count",), None) is not None:
        evidence.append(f"candidate_graph_count={as_int(row['candidate_graph_count'])}")

    signal = build_signal(
        signal_id="code_volume_ratio",
        layer="code",
        value=graph_ratio if graph_ratio is not None else 0,
        evidence=evidence,
        retrieval_features=retrieval_features,
        retrieval_aliases=("cfg_count_ratio_v1", "code_volume_ratio"),
        score=as_float(graph_ratio, 0.0),
    )
    if signal:
        signals.append(signal)
    return signals


def deduplicate_signals(signals: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: dict[tuple[str, str], dict[str, Any]] = {}
    for signal in signals:
        key = (signal["signal_id"], signal["layer"])
        if key not in merged or signal["_sort_strength"] > merged[key]["_sort_strength"]:
            merged[key] = dict(signal)
            continue
        merged[key]["evidence"] = unique_strings(
            merged[key]["evidence"] + signal["evidence"],
            limit=MAX_EVIDENCE_ITEMS,
        )
        merged[key]["used_in_retrieval"] = merged[key]["used_in_retrieval"] or signal["used_in_retrieval"]
        merged[key]["contribution_role"] = "direct" if merged[key]["used_in_retrieval"] else "supporting"
    return list(merged.values())


def sorted_signals(signals: list[dict[str, Any]]) -> list[dict[str, Any]]:
    ordered = sorted(
        signals,
        key=lambda item: (
            -item["_sort_strength"],
            0 if item["used_in_retrieval"] else 1,
            item["signal_id"],
        ),
    )
    if ordered and not any(item["used_in_retrieval"] for item in ordered):
        ordered[0]["used_in_retrieval"] = True
        ordered[0]["contribution_role"] = "direct"
    for index, item in enumerate(ordered[:MAX_DOMINANT_SIGNALS], start=1):
        item["rank"] = index
    return ordered


def infer_matched_layers(signals: list[dict[str, Any]]) -> list[str]:
    per_layer_strength: dict[str, float] = {}
    for signal in signals:
        per_layer_strength[signal["layer"]] = max(
            per_layer_strength.get(signal["layer"], 0.0),
            float(signal["_sort_strength"]),
        )

    matched = [
        layer
        for layer, strength in sorted(per_layer_strength.items(), key=lambda item: (-item[1], item[0]))
        if strength >= 0.35
    ]
    if not matched and per_layer_strength:
        strongest = max(per_layer_strength.items(), key=lambda item: item[1])[0]
        matched = [strongest]
    return matched


def confidence_from_score(retrieval_score: float) -> str:
    if retrieval_score > 0.7:
        return "high"
    if retrieval_score > 0.4:
        return "medium"
    return "low"


def layer_label(layer: str) -> str:
    return layer or "unknown"


def signal_phrase(signal: dict[str, Any]) -> str:
    text = signal["value_text"].strip()
    if text:
        return text
    return SIGNAL_LABELS.get(signal["signal_id"], signal["signal_id"])


def join_human_readable(values: list[str]) -> str:
    cleaned = [value for value in values if value]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} и {cleaned[1]}"
    return ", ".join(cleaned[:-1]) + f" и {cleaned[-1]}"


def build_explanation_text(
    app_a: str,
    app_b: str,
    matched_layers: list[str],
    dominant_signals: list[dict[str, Any]],
    filtered_as_noise: list[dict[str, Any]],
    confidence: str,
) -> str:
    if not dominant_signals:
        return (
            f"Кандидат `{app_b}` включен в короткий список для `{app_a}`, но входной candidate row не содержит "
            "достаточно детализированных сигналов для объяснения причин отбора."
        )

    lead_signal = dominant_signals[0]
    lead_layer = layer_label(lead_signal["layer"])
    first_sentence = (
        f"Кандидат `{app_b}` включен в короткий список для `{app_a}` прежде всего по слою {lead_layer}: "
        f"прямой retrieval-сигнал дали {signal_phrase(lead_signal)}."
    )

    supporting_layers = [layer for layer in matched_layers if layer != lead_signal["layer"]]
    supporting_part = ""
    if supporting_layers:
        supporting_part = (
            f"Поддерживающие совпадения по слоям {join_human_readable(supporting_layers)} усилили включение"
        )

    noise_part = ""
    if filtered_as_noise:
        classes = join_human_readable(
            [item["noise_class"] for item in filtered_as_noise[:3]]
        )
        noise_part = f"{classes} были ослаблены как шум"

    caution_part = ""
    if confidence == "low":
        caution_part = "сигнал первого этапа остается слабым и требует осторожного достраивания модели"
    elif confidence == "medium" and not supporting_part:
        caution_part = "поддержка сигнала остается ограниченной и требует проверки на downstream-этапе"

    second_sentence_parts = [part for part in (supporting_part, noise_part, caution_part) if part]
    if not second_sentence_parts:
        return first_sentence
    return first_sentence + " " + ", а ".join(second_sentence_parts) + "."


def clean_signal(signal: dict[str, Any]) -> dict[str, Any]:
    return {
        "rank": signal["rank"],
        "signal_id": signal["signal_id"],
        "layer": signal["layer"],
        "used_in_retrieval": signal["used_in_retrieval"],
        "contribution_role": signal["contribution_role"],
        "value": signal["value"],
        "value_text": signal["value_text"],
        "evidence": signal["evidence"],
    }


def build_screening_explanation(
    row: dict[str, Any],
    row_index: int,
    pair_index: dict[str, list[dict[str, Any]]],
    app_index: dict[str, list[dict[str, Any]]],
) -> dict[str, Any]:
    app_a = str(get_first(row, ("app_a", "query_app_id", "first"), "")).strip()
    app_b = str(get_first(row, ("app_b", "candidate_app_id", "second"), "")).strip()
    if not app_a or not app_b:
        raise ValueError(f"Candidate row at index {row_index} does not define app ids.")

    retrieval_rank = as_int(get_first(row, ("retrieval_rank", "rank"), row_index + 1), row_index + 1)
    retrieval_score = as_float(get_first(row, ("retrieval_score", "score"), 0.0), 0.0)
    retrieval_features = normalize_retrieval_features(row)

    signals = extract_explicit_signals(row, retrieval_features) + build_metric_signals(row, retrieval_features)
    ordered_signals = sorted_signals(deduplicate_signals(signals))
    dominant_signals = ordered_signals[:MAX_DOMINANT_SIGNALS]
    matched_layers = infer_matched_layers(ordered_signals)
    filtered_as_noise = collect_filtered_noise(app_a, app_b, pair_index, app_index)
    confidence = confidence_from_score(retrieval_score)
    explanation_text = build_explanation_text(
        app_a=app_a,
        app_b=app_b,
        matched_layers=matched_layers,
        dominant_signals=dominant_signals,
        filtered_as_noise=filtered_as_noise,
        confidence=confidence,
    )

    explanation: dict[str, Any] = {
        "format_version": FORMAT_VERSION,
        "query_app_id": app_a,
        "candidate_app_id": app_b,
        "retrieval_rank": retrieval_rank,
        "matched_layers": matched_layers,
        "dominant_signals": [clean_signal(signal) for signal in dominant_signals],
        "filtered_as_noise": filtered_as_noise,
        "retrieval_score": retrieval_score,
        "confidence": confidence,
        "explanation_text": explanation_text,
    }

    # EXEC-088-WRITERS: прокинуть единый формат Evidence, если писатель
    # screening_runner уже записал его на candidate row. Контракт сохраняется
    # (поле добавляется только при наличии непустого списка dict).
    raw_evidence = row.get("evidence")
    if isinstance(raw_evidence, list):
        filtered_evidence = [item for item in raw_evidence if isinstance(item, dict)]
        if filtered_evidence:
            explanation["evidence"] = filtered_evidence

    return {
        "app_a": app_a,
        "app_b": app_b,
        "screening_explanation": explanation,
    }


def build_screening_explanations(
    candidate_payload: Any,
    noise_payload: Any,
) -> list[dict[str, Any]]:
    candidate_rows = normalize_candidate_rows(candidate_payload)
    noise_rows = normalize_noise_rows(noise_payload)
    pair_index, app_index = build_noise_index(noise_rows)

    results = []
    for row_index, row in enumerate(candidate_rows):
        results.append(build_screening_explanation(row, row_index, pair_index, app_index))
    return results


def main() -> None:
    args = parse_args()
    candidate_payload = load_json(Path(args.candidates))
    noise_payload = load_json(Path(args.noise))
    explained_rows = build_screening_explanations(candidate_payload, noise_payload)
    write_json(Path(args.output), explained_rows)
    print(f"rows={len(explained_rows)}")
    print(f"output={Path(args.output)}")


if __name__ == "__main__":
    main()
