#!/usr/bin/env python3
"""Tests for NoiseProfileEnvelope + noise_integration — NC-003.

Tests:
  Unit:
    1. NoiseProfileEnvelope dataclass defaults
    2. to_dict() / from_dict() round-trip
    3. from_dict() tolerance (missing / extra keys)
    4. arbitrate_detector() — library_view_v2 path
    5. arbitrate_detector() — prefix_catalog_v1 fallback
    6. arbitrate_detector() — offline_profile_fingerprint_v1 fallback
    7. arbitrate_detector() — all detectors fail -> blocked envelope
    8. noise_status semantics: clean / noisy / unknown

  Integration:
    9.  inject_noise_into_screening_pair() — warnings merge
    10. inject_noise_into_screening_pair() — explanation fields
    11. propagate_noise_to_pairwise() — artifacts + run_context
    12. add_noise_context_to_explanation() — noise_context block
    13. E2E: arbitrate -> inject_noise -> propagate -> add_context chain
"""

from __future__ import annotations

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from noise_profile_envelope import (
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW,
    DETECTOR_LIBRARY_VIEW_V2,
    DETECTOR_OFFLINE_PROFILE_FINGERPRINT_V1,
    DETECTOR_PREFIX_CATALOG_V1,
    NOISE_STATUS_CLEAN,
    NOISE_STATUS_NOISY,
    NOISE_STATUS_UNKNOWN,
    SCHEMA_VERSION,
    STATUS_BLOCKED,
    STATUS_PARTIAL,
    STATUS_SUCCESS,
    NoiseProfileEnvelope,
    arbitrate_detector,
    from_dict,
    to_dict,
)
from noise_integration import (
    add_noise_context_to_explanation,
    inject_noise_into_screening_pair,
    propagate_noise_to_pairwise,
)


# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

def _make_apk_record(
    library_count: int = 10,
    app_count: int = 5,
    unstable_count: int = 0,
    apk_path: str = "/tmp/test.apk",
    use_v2_signal: bool = False,
    offline_fingerprint: dict | None = None,
) -> dict:
    """Build a minimal mock apk_record dict."""
    reason_lib = "tpl:com.google known library" if use_v2_signal else "known library prefix com.google"
    elements = (
        [{"path": "smali/com/google/Foo.smali", "category": "library_like", "reason": reason_lib}] * library_count
        + [{"path": "smali/com/example/Bar.smali", "category": "app_specific", "reason": "smali file outside library"}] * app_count
        + [{"path": "smali/broken.smali", "category": "unstable_extraction_risk", "reason": "empty smali file"}] * unstable_count
    )
    summary = {
        "library_like": library_count,
        "app_specific": app_count,
        "unstable_extraction_risk": unstable_count,
        "autogenerated_like": 0,
        "packaging_noise": 0,
    }
    record: dict = {
        "apk_path": apk_path,
        "timestamp": "2026-04-16T12:00:00+00:00",
        "elements": elements,
        "summary": summary,
    }
    if offline_fingerprint is not None:
        record["offline_fingerprint"] = offline_fingerprint
    return record


def _make_screening_pair(
    app_a: str = "com.example.alpha",
    app_b: str = "com.example.beta",
    existing_warnings: list | None = None,
) -> dict:
    return {
        "app_a": app_a,
        "app_b": app_b,
        "query_app_id": app_a,
        "candidate_app_id": app_b,
        "retrieval_score": 0.75,
        "screening_warnings": list(existing_warnings or []),
        "screening_explanation": None,
    }


def _make_pairwise_result(pair_id: str = "pair-001") -> dict:
    return {
        "pair_id": pair_id,
        "analysis_status": "complete",
        "artifacts": {
            "artifacts_path": "pairwise://{}".format(pair_id),
        },
        "run_context": {
            "dataset_id": "ds-001",
        },
        "scores": {"jaccard": 0.8},
    }


def _make_explanation(analysis_status: str = "complete") -> dict:
    return {
        "explanation_status": "available",
        "analysis_status": analysis_status,
        "score_interpretation": "high similarity",
    }


# ---------------------------------------------------------------------------
# Unit tests
# ---------------------------------------------------------------------------

def test_envelope_defaults():
    """NoiseProfileEnvelope must have correct schema defaults."""
    e = NoiseProfileEnvelope()
    assert e.schema_version == SCHEMA_VERSION
    assert e.detector_source == DETECTOR_LIBRARY_VIEW_V2
    assert e.confidence == CONFIDENCE_HIGH
    assert e.status == STATUS_SUCCESS
    assert e.noise_status == NOISE_STATUS_UNKNOWN
    assert isinstance(e.downstream_warnings, list)
    assert isinstance(e.evidence_refs, list)
    print("PASS: test_envelope_defaults")


def test_to_dict_from_dict_round_trip():
    """to_dict() / from_dict() must produce identical envelope."""
    original = NoiseProfileEnvelope(
        schema_version=SCHEMA_VERSION,
        detector_source=DETECTOR_PREFIX_CATALOG_V1,
        confidence=CONFIDENCE_MEDIUM,
        status=STATUS_PARTIAL,
        noise_reason="library_ambiguous",
        downstream_warnings=["catalog_only", "fallback_used"],
        evidence_refs=["apk_path:/tmp/x.apk", "timestamp:2026-04-16T12:00:00+00:00"],
        noise_status=NOISE_STATUS_UNKNOWN,
    )
    d = to_dict(original)
    restored = from_dict(d)

    assert restored.schema_version == original.schema_version
    assert restored.detector_source == original.detector_source
    assert restored.confidence == original.confidence
    assert restored.status == original.status
    assert restored.noise_reason == original.noise_reason
    assert restored.downstream_warnings == original.downstream_warnings
    assert restored.evidence_refs == original.evidence_refs
    assert restored.noise_status == original.noise_status

    # Verify copies — mutating dict should not affect original.
    d["downstream_warnings"].append("extra")
    assert len(original.downstream_warnings) == 2, "to_dict must return list copies"
    print("PASS: test_to_dict_from_dict_round_trip")


def test_from_dict_missing_keys():
    """from_dict() must tolerate missing keys with safe defaults."""
    e = from_dict({})
    assert e.schema_version == SCHEMA_VERSION
    assert e.noise_status == NOISE_STATUS_UNKNOWN
    assert e.downstream_warnings == []
    print("PASS: test_from_dict_missing_keys")


def test_from_dict_extra_keys():
    """from_dict() must ignore unknown keys without raising."""
    e = from_dict({"unknown_key": "ignored", "another": 42, "status": STATUS_BLOCKED})
    assert e.status == STATUS_BLOCKED
    print("PASS: test_from_dict_extra_keys")


def test_from_dict_type_error():
    """from_dict() must raise TypeError for non-dict input."""
    try:
        from_dict("not a dict")  # type: ignore[arg-type]
        assert False, "Should have raised TypeError"
    except TypeError:
        pass
    print("PASS: test_from_dict_type_error")


def test_arbitrate_library_view_v2_path():
    """arbitrate_detector with TPL signal should use library_view_v2."""
    record = _make_apk_record(library_count=15, app_count=3, use_v2_signal=True)
    e = arbitrate_detector(record)

    assert e.detector_source == DETECTOR_LIBRARY_VIEW_V2
    assert e.status == STATUS_SUCCESS
    assert e.noise_status == NOISE_STATUS_NOISY
    assert e.confidence == CONFIDENCE_HIGH
    assert "apk_path:/tmp/test.apk" in e.evidence_refs
    print("PASS: test_arbitrate_library_view_v2_path")


def test_arbitrate_prefix_catalog_v1_fallback():
    """arbitrate_detector without TPL signal but with library_like => prefix_catalog_v1."""
    record = _make_apk_record(library_count=8, app_count=2, use_v2_signal=False)
    e = arbitrate_detector(record)

    assert e.detector_source == DETECTOR_PREFIX_CATALOG_V1
    assert e.noise_status == NOISE_STATUS_NOISY
    print("PASS: test_arbitrate_prefix_catalog_v1_fallback")


def test_arbitrate_offline_fingerprint_fallback():
    """arbitrate_detector with offline_fingerprint key uses offline_profile_fingerprint_v1."""
    record = _make_apk_record(library_count=0, app_count=0, use_v2_signal=False)
    record["elements"] = []
    record["summary"] = {}
    record["offline_fingerprint"] = {"is_noisy": True, "version": "v1"}
    e = arbitrate_detector(record)

    assert e.detector_source == DETECTOR_OFFLINE_PROFILE_FINGERPRINT_V1
    assert e.noise_status == NOISE_STATUS_NOISY
    assert "offline_fingerprint_v1_used" in e.downstream_warnings
    print("PASS: test_arbitrate_offline_fingerprint_fallback")


def test_arbitrate_all_detectors_fail():
    """arbitrate_detector with no signal returns blocked unknown envelope."""
    record = {
        "apk_path": "/tmp/empty.apk",
        "timestamp": "2026-04-16T12:00:00+00:00",
        "elements": [],
        "summary": {},
    }
    e = arbitrate_detector(record)

    assert e.status == STATUS_BLOCKED
    assert e.noise_status == NOISE_STATUS_UNKNOWN
    assert e.confidence == CONFIDENCE_LOW
    assert "all_detectors_failed" in e.downstream_warnings
    print("PASS: test_arbitrate_all_detectors_fail")


def test_noise_status_clean():
    """App-specific dominant APK should yield noise_status=clean."""
    record = _make_apk_record(library_count=0, app_count=20, use_v2_signal=False)
    e = arbitrate_detector(record)

    assert e.noise_status == NOISE_STATUS_CLEAN
    assert e.noise_reason == "app_specific_dominant"
    print("PASS: test_noise_status_clean")


def test_noise_status_unknown_partial():
    """Low library ratio (ambiguous) should yield noise_status=unknown, status=partial."""
    record = _make_apk_record(library_count=2, app_count=18, use_v2_signal=False)
    e = arbitrate_detector(record)

    assert e.status == STATUS_PARTIAL
    assert e.noise_status == NOISE_STATUS_UNKNOWN
    assert "ambiguous_library_attribution" in e.downstream_warnings
    print("PASS: test_noise_status_unknown_partial")


# ---------------------------------------------------------------------------
# Integration tests
# ---------------------------------------------------------------------------

def test_inject_noise_into_screening_pair_warnings_merge():
    """inject_noise_into_screening_pair must merge warnings without duplicates."""
    pair = _make_screening_pair(existing_warnings=["pre_existing"])
    envelope = NoiseProfileEnvelope(
        downstream_warnings=["pre_existing", "new_warning"],
        noise_status=NOISE_STATUS_NOISY,
        status=STATUS_SUCCESS,
    )
    result = inject_noise_into_screening_pair(pair, envelope)

    warnings = result["screening_warnings"]
    assert "pre_existing" in warnings
    assert "new_warning" in warnings
    assert warnings.count("pre_existing") == 1, "No duplicates"

    # Original must not be mutated.
    assert pair["screening_warnings"] == ["pre_existing"]
    print("PASS: test_inject_noise_into_screening_pair_warnings_merge")


def test_inject_noise_into_screening_pair_explanation_fields():
    """inject_noise_into_screening_pair must set noise fields in screening_explanation."""
    pair = _make_screening_pair()
    envelope = NoiseProfileEnvelope(
        detector_source=DETECTOR_LIBRARY_VIEW_V2,
        status=STATUS_SUCCESS,
        noise_status=NOISE_STATUS_NOISY,
    )
    result = inject_noise_into_screening_pair(pair, envelope)

    explanation = result["screening_explanation"]
    assert explanation is not None
    assert "noise_profile_ref" in explanation
    assert explanation["noise_status"] == NOISE_STATUS_NOISY
    assert "noise_profile_envelope" in result
    assert result["noise_profile_envelope"]["detector_source"] == DETECTOR_LIBRARY_VIEW_V2
    print("PASS: test_inject_noise_into_screening_pair_explanation_fields")


def test_inject_merges_existing_explanation():
    """inject_noise_into_screening_pair must preserve existing explanation keys."""
    pair = _make_screening_pair()
    pair["screening_explanation"] = {"existing_key": "existing_value"}
    envelope = NoiseProfileEnvelope(noise_status=NOISE_STATUS_CLEAN)
    result = inject_noise_into_screening_pair(pair, envelope)

    explanation = result["screening_explanation"]
    assert explanation["existing_key"] == "existing_value"
    assert "noise_profile_ref" in explanation
    print("PASS: test_inject_merges_existing_explanation")


def test_propagate_noise_to_pairwise_artifacts():
    """propagate_noise_to_pairwise must set noise_profile_ref in artifacts."""
    pairwise = _make_pairwise_result()
    envelope = NoiseProfileEnvelope(
        detector_source=DETECTOR_PREFIX_CATALOG_V1,
        status=STATUS_PARTIAL,
        noise_status=NOISE_STATUS_UNKNOWN,
        confidence=CONFIDENCE_MEDIUM,
    )
    result = propagate_noise_to_pairwise(pairwise, envelope)

    artifacts = result["artifacts"]
    assert "noise_profile_ref" in artifacts
    assert DETECTOR_PREFIX_CATALOG_V1 in artifacts["noise_profile_ref"]
    assert "noise_summary_ref" in artifacts
    assert NOISE_STATUS_UNKNOWN in artifacts["noise_summary_ref"]

    # Original must not be mutated.
    assert "noise_profile_ref" not in pairwise["artifacts"]
    print("PASS: test_propagate_noise_to_pairwise_artifacts")


def test_propagate_noise_to_pairwise_run_context():
    """propagate_noise_to_pairwise must enrich run_context with noise fields."""
    pairwise = _make_pairwise_result()
    envelope = NoiseProfileEnvelope(
        noise_status=NOISE_STATUS_NOISY,
        detector_source=DETECTOR_LIBRARY_VIEW_V2,
    )
    result = propagate_noise_to_pairwise(pairwise, envelope)

    rc = result["run_context"]
    assert rc["noise_status"] == NOISE_STATUS_NOISY
    assert rc["noise_detector_source"] == DETECTOR_LIBRARY_VIEW_V2
    # Preserve existing run_context key.
    assert rc["dataset_id"] == "ds-001"
    print("PASS: test_propagate_noise_to_pairwise_run_context")


def test_propagate_noise_to_pairwise_warnings():
    """propagate_noise_to_pairwise must merge downstream_warnings into pairwise_warnings."""
    pairwise = _make_pairwise_result()
    pairwise["pairwise_warnings"] = ["existing"]
    envelope = NoiseProfileEnvelope(
        downstream_warnings=["existing", "catalog_only"],
        noise_status=NOISE_STATUS_UNKNOWN,
    )
    result = propagate_noise_to_pairwise(pairwise, envelope)

    warnings = result["pairwise_warnings"]
    assert "existing" in warnings
    assert "catalog_only" in warnings
    assert warnings.count("existing") == 1, "No duplicates"
    print("PASS: test_propagate_noise_to_pairwise_warnings")


def test_add_noise_context_to_explanation_fields():
    """add_noise_context_to_explanation must add noise_context block."""
    explanation = _make_explanation()
    envelope = NoiseProfileEnvelope(
        noise_status=NOISE_STATUS_NOISY,
        detector_source=DETECTOR_LIBRARY_VIEW_V2,
        confidence=CONFIDENCE_HIGH,
        noise_reason="library_detected",
        downstream_warnings=[],
        status=STATUS_SUCCESS,
    )
    result = add_noise_context_to_explanation(explanation, envelope)

    nc = result["noise_context"]
    assert nc["noise_status"] == NOISE_STATUS_NOISY
    assert nc["detector_source"] == DETECTOR_LIBRARY_VIEW_V2
    assert nc["confidence"] == CONFIDENCE_HIGH
    assert nc["noise_reason"] == "library_detected"
    assert nc["reliability_degraded"] is False
    # No warnings present => key should not exist.
    assert "warnings" not in nc

    # Original must not be mutated.
    assert "noise_context" not in explanation
    print("PASS: test_add_noise_context_to_explanation_fields")


def test_add_noise_context_reliability_degraded():
    """add_noise_context must flag reliability_degraded for blocked/partial status."""
    explanation = _make_explanation()
    envelope = NoiseProfileEnvelope(
        status=STATUS_BLOCKED,
        noise_status=NOISE_STATUS_UNKNOWN,
        downstream_warnings=["fallback_used"],
    )
    result = add_noise_context_to_explanation(explanation, envelope)

    nc = result["noise_context"]
    assert nc["reliability_degraded"] is True
    assert "warnings" in nc
    assert "fallback_used" in nc["warnings"]
    print("PASS: test_add_noise_context_reliability_degraded")


def test_e2e_arbitrate_inject_propagate_chain():
    """E2E: arbitrate -> inject -> propagate -> add_context chain is consistent."""
    # 1. arbitrate
    record = _make_apk_record(library_count=12, app_count=3, use_v2_signal=True)
    envelope = arbitrate_detector(record)

    assert envelope.detector_source == DETECTOR_LIBRARY_VIEW_V2
    assert envelope.noise_status == NOISE_STATUS_NOISY

    # 2. inject into screening pair
    pair = _make_screening_pair()
    pair_with_noise = inject_noise_into_screening_pair(pair, envelope)

    assert pair_with_noise["screening_explanation"]["noise_status"] == NOISE_STATUS_NOISY
    assert "noise_profile_envelope" in pair_with_noise

    # 3. propagate to pairwise
    pairwise = _make_pairwise_result()
    pairwise_with_noise = propagate_noise_to_pairwise(pairwise, envelope)

    assert pairwise_with_noise["run_context"]["noise_status"] == NOISE_STATUS_NOISY
    assert "noise_profile_ref" in pairwise_with_noise["artifacts"]

    # 4. add context to explanation
    explanation = _make_explanation()
    enriched_explanation = add_noise_context_to_explanation(explanation, envelope)

    nc = enriched_explanation["noise_context"]
    assert nc["detector_source"] == DETECTOR_LIBRARY_VIEW_V2
    assert nc["noise_status"] == NOISE_STATUS_NOISY
    assert nc["schema_version"] == SCHEMA_VERSION

    # Consistency: noise_status is the same across all three stages.
    assert (
        pair_with_noise["screening_explanation"]["noise_status"]
        == pairwise_with_noise["run_context"]["noise_status"]
        == nc["noise_status"]
        == NOISE_STATUS_NOISY
    )
    print("PASS: test_e2e_arbitrate_inject_propagate_chain")


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def run_all_tests():
    tests = [
        test_envelope_defaults,
        test_to_dict_from_dict_round_trip,
        test_from_dict_missing_keys,
        test_from_dict_extra_keys,
        test_from_dict_type_error,
        test_arbitrate_library_view_v2_path,
        test_arbitrate_prefix_catalog_v1_fallback,
        test_arbitrate_offline_fingerprint_fallback,
        test_arbitrate_all_detectors_fail,
        test_noise_status_clean,
        test_noise_status_unknown_partial,
        test_inject_noise_into_screening_pair_warnings_merge,
        test_inject_noise_into_screening_pair_explanation_fields,
        test_inject_merges_existing_explanation,
        test_propagate_noise_to_pairwise_artifacts,
        test_propagate_noise_to_pairwise_run_context,
        test_propagate_noise_to_pairwise_warnings,
        test_add_noise_context_to_explanation_fields,
        test_add_noise_context_reliability_degraded,
        test_e2e_arbitrate_inject_propagate_chain,
    ]

    failed = []
    for test in tests:
        try:
            test()
        except Exception as exc:
            import traceback
            print("FAIL: {} — {}".format(test.__name__, exc))
            traceback.print_exc()
            failed.append(test.__name__)

    print("\n{}/{} tests passed.".format(len(tests) - len(failed), len(tests)))
    if failed:
        print("Failed:", failed)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(run_all_tests())
