#!/usr/bin/env python3
"""Tests for NoiseProfileEnvelope — NC-003-IMPL Step 1+2.

Tests:
  1. NoiseProfileEnvelope serialization (to_dict round-trip).
  2. build_noise_profile() with mock noise_normalizer output.
  3. screening_runner correctly threads downstream_warnings.
"""

from __future__ import annotations

import sys
import os

# Ensure script directory is importable when run directly.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from noise_profile import (
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW,
    DETECTOR_LIBRARY_VIEW_V2,
    DETECTOR_PREFIX_CATALOG_V1,
    SCHEMA_VERSION,
    STATUS_BLOCKED,
    STATUS_PARTIAL,
    STATUS_SUCCESS,
    NoiseProfileEnvelope,
    build_noise_profile,
    to_dict,
)
from screening_runner import _extract_noise_profile_fields, build_candidate_list


# ---------------------------------------------------------------------------
# Helper fixtures
# ---------------------------------------------------------------------------

def _make_apk_result(
    library_count: int = 10,
    app_count: int = 5,
    unstable_count: int = 0,
    apk_path: str = "/tmp/test.apk",
) -> dict:
    """Build a minimal mock noise_normalizer output dict."""
    elements = (
        [{"path": "smali/com/google/Foo.smali", "category": "library_like", "reason": "known library prefix com.google"}] * library_count
        + [{"path": "smali/com/example/Bar.smali", "category": "app_specific", "reason": "smali file outside library"}] * app_count
        + [{"path": "smali/broken.smali", "category": "unstable_extraction_risk", "reason": "empty smali file"}] * unstable_count
    )
    summary = {
        "library_like": library_count,
        "app_specific": app_count,
        "unstable_extraction_risk": unstable_count,
        "autogenerated_like": 0,
        "packaging_noise": 0,
    }
    return {
        "apk_path": apk_path,
        "timestamp": "2026-04-16T00:00:00+00:00",
        "elements": elements,
        "summary": summary,
    }


def _make_app_record(app_id: str, envelope_dict: dict | None = None) -> dict:
    """Build a minimal app_record as used by screening_runner."""
    record: dict = {
        "app_id": app_id,
        "layers": {
            "code": {"dex:classes.dex"},
            "component": set(),
            "resource": set(),
            "metadata": {"apk_name:{}".format(app_id)},
            "library": set(),
        },
        "apk_path": None,
    }
    if envelope_dict is not None:
        record["noise_profile_envelope"] = envelope_dict
    return record


# ---------------------------------------------------------------------------
# Test 1: NoiseProfileEnvelope serialization
# ---------------------------------------------------------------------------

def test_to_dict_round_trip():
    """to_dict() must produce a plain dict with all required schema fields."""
    envelope = NoiseProfileEnvelope(
        schema_version=SCHEMA_VERSION,
        detector_source=DETECTOR_LIBRARY_VIEW_V2,
        confidence=CONFIDENCE_HIGH,
        status=STATUS_SUCCESS,
        noise_reason="library_detected",
        downstream_warnings=["ambiguous_library_attribution"],
        evidence_refs=["apk_path:/tmp/test.apk"],
    )
    result = to_dict(envelope)

    assert isinstance(result, dict), "to_dict must return dict"
    assert result["schema_version"] == SCHEMA_VERSION
    assert result["detector_source"] == DETECTOR_LIBRARY_VIEW_V2
    assert result["confidence"] == CONFIDENCE_HIGH
    assert result["status"] == STATUS_SUCCESS
    assert result["noise_reason"] == "library_detected"
    assert result["downstream_warnings"] == ["ambiguous_library_attribution"]
    assert result["evidence_refs"] == ["apk_path:/tmp/test.apk"]

    # Verify it is a copy — mutating result must not affect envelope.
    result["downstream_warnings"].append("extra")
    assert len(envelope.downstream_warnings) == 1, "to_dict must return a copy of lists"

    print("PASS: test_to_dict_round_trip")


def test_default_envelope_fields():
    """Default NoiseProfileEnvelope must have correct schema defaults."""
    envelope = NoiseProfileEnvelope()
    assert envelope.schema_version == SCHEMA_VERSION
    assert envelope.detector_source == DETECTOR_LIBRARY_VIEW_V2
    assert envelope.confidence == CONFIDENCE_HIGH
    assert envelope.status == STATUS_SUCCESS
    assert isinstance(envelope.downstream_warnings, list)
    assert isinstance(envelope.evidence_refs, list)

    print("PASS: test_default_envelope_fields")


# ---------------------------------------------------------------------------
# Test 2: build_noise_profile() with mock noise_normalizer output
# ---------------------------------------------------------------------------

def test_build_noise_profile_library_dominant():
    """build_noise_profile on library-dominant APK => status=success, confidence=high."""
    apk_result = _make_apk_result(library_count=20, app_count=2, unstable_count=0)
    envelope = build_noise_profile(apk_result)

    assert envelope.status == STATUS_SUCCESS
    assert envelope.confidence == CONFIDENCE_HIGH
    assert envelope.noise_reason == "library_detected"
    assert "extraction_unstable" not in envelope.downstream_warnings
    assert "apk_path:/tmp/test.apk" in envelope.evidence_refs
    assert "timestamp:2026-04-16T00:00:00+00:00" in envelope.evidence_refs

    print("PASS: test_build_noise_profile_library_dominant")


def test_build_noise_profile_with_unstable():
    """build_noise_profile with unstable elements => status=success|partial, confidence=medium."""
    apk_result = _make_apk_result(library_count=10, app_count=5, unstable_count=2)
    envelope = build_noise_profile(apk_result)

    # Should still be success (library > 50%) but with medium confidence and warnings.
    assert envelope.status in (STATUS_SUCCESS, STATUS_PARTIAL)
    assert envelope.confidence in (CONFIDENCE_MEDIUM, CONFIDENCE_LOW)
    assert "extraction_unstable" in envelope.downstream_warnings

    print("PASS: test_build_noise_profile_with_unstable")


def test_build_noise_profile_empty_result():
    """build_noise_profile on empty APK result => status=blocked."""
    apk_result = {
        "apk_path": "/tmp/empty.apk",
        "timestamp": "2026-04-16T00:00:00+00:00",
        "elements": [],
        "summary": {},
    }
    envelope = build_noise_profile(apk_result)

    assert envelope.status == STATUS_BLOCKED
    assert envelope.confidence == CONFIDENCE_LOW
    assert "fallback_used" in envelope.downstream_warnings

    print("PASS: test_build_noise_profile_empty_result")


def test_build_noise_profile_partial_library():
    """build_noise_profile with low library ratio => status=partial."""
    # 2 library out of 20 total = 10%, below 50% threshold.
    apk_result = _make_apk_result(library_count=2, app_count=18, unstable_count=0)
    envelope = build_noise_profile(apk_result)

    assert envelope.status == STATUS_PARTIAL
    assert "ambiguous_library_attribution" in envelope.downstream_warnings

    print("PASS: test_build_noise_profile_partial_library")


def test_build_noise_profile_evidence_refs():
    """build_noise_profile must include apk_path and timestamp in evidence_refs."""
    apk_result = _make_apk_result()
    envelope = build_noise_profile(apk_result)

    refs = envelope.evidence_refs
    assert any("apk_path:" in r for r in refs), "evidence_refs must include apk_path"
    assert any("timestamp:" in r for r in refs), "evidence_refs must include timestamp"

    print("PASS: test_build_noise_profile_evidence_refs")


# ---------------------------------------------------------------------------
# Test 3: screening_runner correctly threads downstream_warnings
# ---------------------------------------------------------------------------

def test_extract_noise_profile_fields_no_envelope():
    """_extract_noise_profile_fields returns empty when no envelope present."""
    app_record = _make_app_record("com.example.app")
    warnings, ref = _extract_noise_profile_fields(app_record)

    assert warnings == []
    assert ref is None

    print("PASS: test_extract_noise_profile_fields_no_envelope")


def test_extract_noise_profile_fields_with_envelope():
    """_extract_noise_profile_fields extracts warnings and builds ref correctly."""
    envelope_dict = to_dict(NoiseProfileEnvelope(
        detector_source=DETECTOR_PREFIX_CATALOG_V1,
        status=STATUS_PARTIAL,
        downstream_warnings=["catalog_only", "fallback_used"],
    ))
    app_record = _make_app_record("com.example.app", envelope_dict=envelope_dict)
    warnings, ref = _extract_noise_profile_fields(app_record)

    assert "catalog_only" in warnings
    assert "fallback_used" in warnings
    assert ref is not None
    assert DETECTOR_PREFIX_CATALOG_V1 in ref
    assert STATUS_PARTIAL in ref
    assert SCHEMA_VERSION in ref

    print("PASS: test_extract_noise_profile_fields_with_envelope")


def test_screening_runner_propagates_warnings():
    """build_candidate_list must propagate downstream_warnings into screening_warnings."""
    envelope_dict = to_dict(NoiseProfileEnvelope(
        detector_source=DETECTOR_LIBRARY_VIEW_V2,
        status=STATUS_PARTIAL,
        confidence=CONFIDENCE_MEDIUM,
        noise_reason="library_ambiguous",
        downstream_warnings=["ambiguous_library_attribution", "fallback_used"],
        evidence_refs=["apk_path:/tmp/a.apk"],
    ))

    app_a = _make_app_record("com.example.alpha", envelope_dict=envelope_dict)
    app_b = _make_app_record("com.example.beta")

    # Use a minimal cascade config: features=code, metric=jaccard, threshold=0.0.
    import tempfile
    import json
    config = {
        "stages": {
            "screening": {
                "features": ["code"],
                "metric": "jaccard",
                "threshold": 0.0,
            }
        }
    }
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(config, f)
        config_path = f.name

    from screening_runner import run_screening

    candidate_list = run_screening(
        cascade_config_path=config_path,
        app_records=[app_a, app_b],
    )

    assert len(candidate_list) >= 1, "Should produce at least one candidate pair"

    # Find the pair where alpha is query_app_id.
    alpha_rows = [c for c in candidate_list if c["query_app_id"] == "com.example.alpha"]
    assert len(alpha_rows) >= 1, "alpha should appear as query app"

    row = alpha_rows[0]
    assert "ambiguous_library_attribution" in row["screening_warnings"], (
        "downstream_warnings must be threaded into screening_warnings"
    )
    assert "fallback_used" in row["screening_warnings"]
    assert row["screening_explanation"] is not None
    assert "noise_profile_ref" in row["screening_explanation"]

    print("PASS: test_screening_runner_propagates_warnings")


def test_screening_runner_no_envelope_no_warnings():
    """build_candidate_list with no envelope produces empty screening_warnings."""
    app_a = _make_app_record("com.example.gamma")
    app_b = _make_app_record("com.example.delta")

    import tempfile
    import json
    config = {
        "stages": {
            "screening": {
                "features": ["code"],
                "metric": "jaccard",
                "threshold": 0.0,
            }
        }
    }
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(config, f)
        config_path = f.name

    from screening_runner import run_screening

    candidate_list = run_screening(
        cascade_config_path=config_path,
        app_records=[app_a, app_b],
    )

    assert len(candidate_list) >= 1
    for row in candidate_list:
        assert row["screening_warnings"] == [], "No envelope => no warnings"
        assert row["screening_explanation"] is None, "No envelope => no noise_profile_ref"

    print("PASS: test_screening_runner_no_envelope_no_warnings")


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def run_all_tests():
    tests = [
        test_to_dict_round_trip,
        test_default_envelope_fields,
        test_build_noise_profile_library_dominant,
        test_build_noise_profile_with_unstable,
        test_build_noise_profile_empty_result,
        test_build_noise_profile_partial_library,
        test_build_noise_profile_evidence_refs,
        test_extract_noise_profile_fields_no_envelope,
        test_extract_noise_profile_fields_with_envelope,
        test_screening_runner_propagates_warnings,
        test_screening_runner_no_envelope_no_warnings,
    ]

    failed = []
    for test in tests:
        try:
            test()
        except Exception as exc:
            print("FAIL: {} — {}".format(test.__name__, exc))
            failed.append(test.__name__)

    print("\n{}/{} tests passed.".format(len(tests) - len(failed), len(tests)))
    if failed:
        print("Failed:", failed)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(run_all_tests())
